### ISSUE TITLE
Update Prisma guidance with latest PlanetScale recommendations

### ISSUE THREAD

**Issue by leerob** [vercel/platforms#10]
Making things even easier 😄 

https://docs.planetscale.com/tutorials/automatic-prisma-migrations

**Comment by leerob** [comment]
Need to update [the guide](https://vercel.com/guides/nextjs-multi-tenant-application#2.-set-up-your-mysql-database) as well, since a shadow database wouldn't be needed with `db push`.

**Comment by DevDaveJ** [comment]
> Making things even easier 😄
> 
> https://docs.planetscale.com/tutorials/automatic-prisma-migrations

Hi. Tried to follow the guide in the link. I got stuck at the line to connect to the db:
pscale shell platforms main

Th terminal just hangs there non-responsive, doesnt return, doesnt show an error.

Where are error logs, please?

**Comment by ariband5** [comment]
Receiving these two errors `Error: Get config: Schema Parsing P1012`  and `error: Environment variable not found: DATABASE URL.` when I run `npx prisma migrate dev --name init`. Any ideas what the problem could be?

**Comment by steven-tey** [comment]
@ariband5 you need to add the `DATABASE_URL` as a variable in your `.env` file. You can copy that string from Planetscale when you generate a password.

**Comment by ariband5** [comment]
Thank you @steven-tey! My `.env` file was incorrectly named `.env.example`.

**Comment by steven-tey** [comment]
@ariband5 great feedback, I've added a note in the official guide to change the name of `.env.example` to `.env`.
