### ISSUE TITLE
Error while adding custom domains

### ISSUE THREAD

**Issue by T4533N** [vercel/platforms#101]
Seems like a planetscale issue? 

![image](https://user-images.githubusercontent.com/44163644/165721259-99e2862c-4fd5-4250-9057-daf36f150ded.png)

**Comment by steven-tey** [comment]
@T4533N This should be fixed by https://github.com/vercel/platforms/pull/105

So sorry for the weird bug, I was a Typescript noob when I first built this 😅

**Comment by steven-tey** [comment]
@T4533N This should be fixed by https://github.com/vercel/platforms/pull/105

So sorry for the weird bug, I was a Typescript noob when I first built this 😅
