### ISSUE TITLE
Access control on API ?

### ISSUE THREAD

**Issue by crubier** [vercel/platforms#11]
I might be missing something, but it seems to me that the API is insecure, the api routes don’t check anything, so anyone can issue requests to delete or modify any existing content from other spaces for example.

**Comment by huv1k** [comment]
Yes, best practices in their finest 😅 It's happening a lot that there is a lot of "examples", "templates" and people blindly copy and nobody teaches good practices and this is kind of sad.

**Comment by NuroDev** [comment]
Currently working on the migration to TypeScript (#15) I too noticed this and, to add some kind of request sanitisation, starting adding request method checks along the way. Though I feel like more should be added to stop any potentially malicious requests

**Comment by leerob** [comment]
https://github.com/vercel/platforms/pull/25

**Comment by steven-tey** [comment]
Merged #25 and fixed this, thanks @crubier for the headsup!
