### ISSUE TITLE
"ikm" must be at least one byte in length

### ISSUE THREAD

**Issue by hanymorcos** [vercel/platforms#114]
Any thoughts on what is the issue?

thanks
Hany
https://next-auth.js.org/warnings#no_secret
[next-auth][warn][NO_SECRET] 
https://next-auth.js.org/warnings#no_secret
[next-auth][error][GET_AUTHORIZATION_URL_ERROR] 
https://next-auth.js.org/errors#get_authorization_url_error "ikm" must be at least one byte in length {
  message: '"ikm" must be at least one byte in length',
  stack: 'TypeError: "ikm" must be at least one byte in length\n' +
    '    at normalizeIkm (/Users/hanymorcos/projects/platforms/node_modules/@panva/hkdf/dist/node/cjs/index.js:26:15)\n' +
    '    at hkdf (/Users/hanymorcos/projects/platforms/node_modules/@panva/hkdf/dist/node/cjs/index.js:47:60)\n' +

**Comment by toritroniks** [comment]
same here.

```
provider: {
    id: 'github',
    name: 'GitHub',
    type: 'oauth',
    authorization: {
      url: 'https://github.com/login/oauth/authorize',
      params: [Object]
    },
    token: { url: 'https://github.com/login/oauth/access_token', params: {} },
    userinfo: {
      url: 'https://api.github.com/user',
      request: [AsyncFunction: request]
    },
    profile: [Function: profile],
    idToken: false,
    checks: [ 'state' ],
    clientId: 'xxxxxxxxxxxx',
    clientSecret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    signinUrl: 'http://app.localhost:3000/api/auth/signin/github',
    callbackUrl: 'http://app.localhost:3000/api/auth/callback/github'
  },
  message: '"ikm" must be at least one byte in length'
}
```

**Comment by toritroniks** [comment]
@hanymorcos 
just figured it out.. you need to set something in the `SECRET` environment variable

you can generate a secret with here: https://generate-secret.vercel.app/32

for some reason I thought this variable was not required in localhost, but it is.
