### ISSUE TITLE
issue with MDXRemote. 

### ISSUE THREAD

**Issue by hanymorcos** [vercel/platforms#115]
I was getting errors after vercel deployment. I installed error bound package and received the following error message. 

thanks,

Hany

./pages/_sites/[site]/[slug].tsx:129:40
Type error: Type '{ a: (options: { href: string; } & { children?: ReactNode; }) => JSX.Element; BlurImage: (props: BlurImageProps) => JSX.Element; Examples: ({ data }: ExamplesProps) => JSX.Element; Tweet: ({ id, metadata, className }: TweetProps) => JSX.Element; }' is not assignable to type 'Record<string, ReactNode>'.
  Property 'a' is incompatible with index signature.
    Type '(options: { href: string; } & { children?: ReactNode; }) => Element' is not assignable to type 'ReactNode'.

  127 | 
  128 |       <article className="w-11/12 sm:w-3/4 m-auto prose prose-md sm:prose-lg">
> 129 |         <MDXRemote {...data.mdxSource} components={components} />
      |                                        ^
  130 |       </article>
  131 | 
  132 |       {adjacentPosts.length > 0 && (
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by OlehObodin** [comment]
Got the same on react 17,
 force fix : a: link as any in components object
