### ISSUE TITLE
Error with Cloudinary upload widget

### ISSUE THREAD

**Issue by ragingwind** [vercel/platforms#12]
I would like to use eslint with `next/core-web-vitals` but it causes build fail with below:

```
./components/Cloudinary.js
39:11  Error: External synchronous scripts are forbidden. See: https://nextjs.org/docs/messages/no-sync-scripts  @next/next/no-sync-scripts
```

AFAIK, external synchronous scripts can't be used and placed in `Head`. How to fix it, or any recommendation for workaround?

**Comment by steven-tey** [comment]
Good question, looping in the Cloudinary team to help with this, seems like the issue is isolated to the upload widget

**Comment by dlisjak** [comment]
Have you tried using npm i cloudinary package?

**Comment by steven-tey** [comment]
Closing this since we've moved from Cloudinary to [Vercel Blob](https://vercel.com/storage/blob) :)
