### ISSUE TITLE
Revalidation is not working

### ISSUE THREAD

**Issue by 0x6c23** [vercel/platforms#124]
When I build locally by next build and next start I can revalidate and it works, however, when I deploy this to vercel it won't revalidate anymore.

Weird is, that revalidation only works with ``/_sites/blog/{id}`` instead of ``/{id}`` even though the rewrite is set in middleware and the validation happens on blog.domain.com. I get "OK" on the /_site.. requests and ``failed to revalidate`` on everything else.

When I revalidate after deploying (using /_sites/...) I can disable the cache and refresh the page and for a split second I see the new version but than it changes back to the old one. 

I use this for a fixed path ``blog`` so I changed the getStaticPaths/ Props:

``pages/_sites/[site]/index``

```javascript
export const getStaticPaths = async () => {
  return { paths: [{ params: { site: "blog" }}], fallback: true }
};

export const getStaticProps = async ({
  params,
}) => {
  const data = (await prisma.post.findMany({
    where: {
      published: true,
    },
    orderBy: {
      createdAt: "desc",
    },
  }));

  if (!data) return { notFound: true, revalidate: 10 };

  return {
    props: {
      stringifiedData: JSON.stringify({
        [...]
      }),
    },
    revalidate: 3600,
  };
};
```

``pages/_sites/[site]/[slug]``

```javascript
export const getStaticPaths = async () => {
  const posts = await prisma.post.findMany({
    select: {
      slug: true,
    },
  });

  const paths = posts.flatMap((post) => {
    return {
      params: {
        site: "blog",
        slug: post.slug,
      },
    };
  })

  return {
    paths,
    fallback: true,
  };
};


export const getStaticProps = async ({
  params,
}) => {
  if (!params) throw new Error("No path parameters found");

  const { slug } = params;

  const data = (await prisma.post.findFirst({
    where: {
      slug
    }
  }));

  if (!data) return { notFound: true, revalidate: 10 };

  const [mdxSource, adjacentPosts] = await Promise.all([
    getMdxSource(data.content),
    prisma.post.findMany({
      where: {
        published: true,
        NOT: {
          id: data.id,
        },
      },
      select: {
        slug: true,
        title: true,
        createdAt: true,
        description: true,
        image: true,
        imageBlurhash: true,
      },
    }),
  ]);

  return {
    props: {
      stringifiedData: JSON.stringify({
        ...data,
        mdxSource,
      }),
      stringifiedAdjacentPosts: JSON.stringify(adjacentPosts),
    },
    revalidate: 3600,
  };
};
```

And ``middleware``

```javascript
export const config = {
  matcher: [
    "/",
    "/([^/.]*)", // exclude `/public` files by matching all paths except for paths containing `.` (e.g. /logo.png)
    "/site/:path*",
    "/post/:path*",
    "/_sites/:path*",
  ],
};

export default function middleware(req) {
  // Clone the request url
  const url = req.nextUrl.clone();
  
  const { pathname } = req.nextUrl;
  
  const hostname = req.headers.get("host");
  if (!hostname)
    return new Response(null, {
      status: 400,
      statusText: "No hostname found in request headers",
    });


  const currentHost =
    process.env.NODE_ENV === "production" && process.env.VERCEL === "1"
      ? hostname
      .replace(`.domain.org`, "")
      .replace(`.###.vercel.app`, "")
      : hostname.replace(`.localhost:3000`, "");

  if(process.env.NODE_ENV !== "production") {
    if(pathname.startsWith(`/_templates`)) {
      url.pathname = pathname
      return NextResponse.rewrite(url);
    }
  }

  if (pathname.startsWith(`/_sites`) || pathname.startsWith(`/_templates`))
    return new Response(null, {
      status: 404,
    });


  if (!pathname.includes(".") && !pathname.startsWith("/api")) {
    if (currentHost === "app") {
      if (
        pathname === "/login" &&
        (req.cookies["next-auth.session-token"] ||
          req.cookies["__Secure-next-auth.session-token"])
      ) {
        url.pathname = "/";
        return NextResponse.redirect(url);
      }

      url.pathname = `/app${pathname}`;
      return NextResponse.rewrite(url);
    }

    if (
      hostname === "localhost:3000" ||
      hostname === "domain.org" ||
      hostname === "###.vercel.app"
    ) {
      url.pathname = `/home${url.pathname}`;
      return NextResponse.rewrite(url);
    }

    if(currentHost === "blog") {
      url.pathname = `/_sites/${currentHost}${url.pathname}`;
      return NextResponse.rewrite(url);
    }
    
    
    url.pathname = `/_templates/router`;
    return NextResponse.rewrite(url);
  }
```

Any idea?

**Comment by 0x6c23** [comment]
Same happens when manually putting the bypassToken into ``x-prerender-revalidate`` and calling the endpoints.

When I call ``/_sites/blog/id`` I get a cache header of ``REVALIDATED`` but the same problem persists, when deployed on vercel the site initially loads the new version but than reverts to the old one.

When I call ``/id`` I get cache header ``HIT`` and nothing happens.

**Comment by ahanusek** [comment]
Have similar issues when trying to revalidate page for subdomain. I'm just sending request to URL below:

`https://subdomain.domain.pl/api/revalidate?secret=token&page=pagePath`

api/revalidate.ts

```
export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  // Check for secret to confirm this is a valid request
  if (req.query.secret !== process.env.REVALIDATE_API_TOKEN) {
    return res.status(401).json({ message: 'Invalid token' });
  }
  const path = String(req.query.page);
  // eslint-disable-next-line no-console
  console.log(`Revalidating page: ${path} for host ${req.headers.host}`, { header: req.headers });
  try {
    // this should be the actual path not a rewritten path
    // e.g. for "/blog/[slug]" this should be "/blog/post-1"
    await res.revalidate(`/${path}`);
    return res.json({ revalidated: true });
  } catch (err) {
    // If there was an error, Next.js will continue
    // to show the last successfully generated page
    // @ts-ignore
    // eslint-disable-next-line no-console
    console.log('Error when updating url', path, err?.message, err);
    return res.status(500).send('Error revalidating');
  }
}
```

And getting 404 

> Failed to revalidate /pagePath: Invalid response 404

But when I'm just copy this path and use together with the url https://subdomain.domain.pl, in browser it works perfectly fine, so page exists. My middleware.ts is the exactly same like in this repo. Any hint how to solve that issue?

**Comment by steven-tey** [comment]
Hey @0x6c23 @ahanusek! Apologies for this – this is due to the fact that [Middleware doesn't execute for on-demand ISR requests](https://github.com/vercel/next.js/issues/36092#issuecomment-1180931062), which means you have to put the exact URL that you want revalidated. 

In this case, that's `/_sites/${siteId}/${slug}` and it has to be sent to the same hostname that you want revalidated.

I've updated the code for the [`revalidate()` function](https://github.com/vercel/platforms/blob/main/lib/revalidate.ts) and [the part where it's called](https://github.com/vercel/platforms/blob/main/lib/api/post.ts#L243-L258) to account for this.

**Comment by ahanusek** [comment]
@steven-tey Thanks, now the path is proper and page is revalidated, but there is another issue in Next.js =>

https://github.com/vercel/next.js/issues/38306

So now, page is revalidated, I see that rendered HTML has refreshed data, but after that endpoint with .json data (https://subdomain.domian.pl/_next/data/build_number/pl/p/dynamic_page_name.json) return stale data from cache and overwrite view.

**Comment by 0x6c23** [comment]
> @steven-tey Thanks, now the path is proper and page is revalidated, but there is another issue in Next.js =>
> 
> [vercel/next.js#38306](https://github.com/vercel/next.js/issues/38306)
> 
> So now, page is revalidated, I see that rendered HTML has refreshed data, but after that endpoint with .json data (https://subdomain.domian.pl/_next/data/build_number/pl/p/dynamic_page_name.json) return stale data from cache and overwrite view (maybe is somehow connected with next-i18next locales).

Exactly the same issue I'm having, which I also described while creating this issue. Pages get revalidated but when opening them they get overwritten by the old version after a split second. Not using locales.

**Comment by steven-tey** [comment]
Thanks for the bug report @ahanusek @0x6c23 – this should've been fixed with https://github.com/vercel/next.js/issues/38306, you'll just need to deploy the application :)

**Comment by ahanusek** [comment]
Yep, works for me. Thanks.
