### ISSUE TITLE
500 server error when trying to access a custom domain - custom domain issue

### ISSUE THREAD

**Issue by MohamedHakem** [vercel/platforms#126]
Hi, I'm working on a platform using `Next.js 12.0.11-canary.8`  

This is my case 

- The main domain is:  `maindomain.com` in production and `localhost:3000` in development
- Each user gets a random subdomain like: `gogdf.maindomain.com` or `gogdf.localhost:3000` in development

- Each user can add a custom domain that they own from a registrar (for example namecheap) and the domain is added successfully to the team's project (the platform I'm working on) 

- After that the user points their domain DNS configurations to vercel's nameservers or an A record `76.76.21.21` 

- Everything is working fine, the domain is added to Vercel and points to Vercel

- When I try to access the custom domain (for example `newdomain.com`) home page (`newdomain.com/`) the page works as expected, **BUT** when I try to access any page that's not the homepage (root, `'/'`) or any pathname like newdomain.com/signup is gives me an `error 404,` and when I try to access a page that requires a logged-in/session user such as `newdomain.com/myaccount` it gives me a `500 server error` 

Here's my _middleware.js file to check if there's an error with my current state that make the main domain (maindomain.com) works fine, the subdomains (usersite.maindomain.com) works fine, the custom domains (newdomain.com/) home page only also works fine, but prevents the custom domains paths other than homepage to work properly. 

_middleware.js 

```
import { NextResponse } from "next/server";

export default function middleware(req) {
  const url = req.nextUrl.clone(); // clone the request url
  const { pathname } = req.nextUrl; // get pathname of request (e.g. /blog-slug)
  const hostname = req.headers.get("host"); // get hostname of request (e.g. demo.vercel.pub)

  // only for demo purposes – remove this if you want to use your root domain as the landing page
  // if (hostname === "vercel.pub" || hostname === "platforms.vercel.app") {
  //   return NextResponse.redirect("https://demo.vercel.pub");
  // }

  const currentHost =
    process.env.NODE_ENV === "production" && process.env.VERCEL === "1"
      ? hostname.replace(`.maindomain.com`, "")
      : hostname.replace(`.localhost:3000`, "");

  if (!pathname.includes(".") && !pathname.startsWith("/api")) {
    if (currentHost == "app") {
      if (
        (pathname === "/login" || pathname === "/signup") &&
        (req.cookies["next-auth.session-token"] ||
          req.cookies["__Secure-next-auth.session-token"])
      ) {
        url.pathname = "/";
        return NextResponse.redirect(url);
      }
      url.pathname = `/app${pathname}`;
      return NextResponse.rewrite(url);
    }
    if (currentHost == "admin") {
      url.pathname = `/admin${pathname}`;
      return NextResponse.rewrite(url);
    }
    if (currentHost == "patient") {
      url.pathname = `/patient${pathname}`;
      return NextResponse.rewrite(url);
    }
    if (currentHost == "doctor") {
      url.pathname = `/doctor${pathname}`;
      return NextResponse.rewrite(url);
    }
    if (
      pathname === "/login" &&
      (req.cookies["next-auth.session-token"] ||
        req.cookies["__Secure-next-auth.session-token"])
    ) {
      url.pathname = "/";
      return NextResponse.redirect(url);
    }
    if (hostname === "localhost:3000" || hostname === "maindomain.com") {
      url.pathname = `/home${pathname}`;
      return NextResponse.rewrite(url);
    }
    // tried to replace {currentHost} with {hostname} but same issue persist. 
    url.pathname = `/_sites/${currentHost}${pathname}`;  
    return NextResponse.rewrite(url);
  }
}
```

Feel free to ask me anything or to provide more information about my situation. 

I'm waiting for your response, I need to fix this as soon as possible. 

Thank you.

**Comment by steven-tey** [comment]
Hey Mohamed! So sorry for the late response – this should've been fixed with our [new middleware here](https://github.com/vercel/platforms/blob/main/middleware.ts). Specifically, [this matcher regex](https://github.com/vercel/platforms/blob/main/middleware.ts#L23) should match everything from `/login` to `/myaccount` to `/signup` – except for public files like `/thumbnail.png`.
