### ISSUE TITLE
Requesting domain delegation deprecated?

### ISSUE THREAD

**Issue by alisalahio** [vercel/platforms#128]
We're using Vercel Platforms at Instatus and loving it.

Noticed that domain delegation endpoint is deprecated. 
Is there an alternative way to display to customers what do they need to do in case their domain is used by another team?

**Comment by steven-tey** [comment]
Hey Ali! We recently rolled out [self-serve delegation of subdomains](https://vercel.com/changelog/self-serve-delegation-of-subdomains) so you can now use the [Domains Verify API endpoint](https://vercel.com/docs/rest-api#endpoints/projects/verify-project-domain) to do so.
