### ISSUE TITLE
Error: Get config: Schema Parsing P1012

### ISSUE THREAD

**Issue by shugert** [vercel/platforms#13]
When running `npx prisma migrate dev --name init` I am getting the following error:

```
Prisma schema loaded from prisma/schema.prisma
Error: Get config: Schema Parsing P1012

error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:6
   | 
 5 |   provider             = "mysql"
 6 |   url                  = env("DATABASE_URL")
   | 

Validation Error Count: 1

```

And the migration is not loading into planetscale staging branch or anywhere else for that matter. 

Any thoughts?

Thanks

**Comment by NuroDev** [comment]
Looking at the error it looks like Prisma cannot find the `DATABASE_URL` environment variable.
Have you copied the `.env.example` into a new `.env` file?

**Comment by shugert** [comment]
That did it! thanks.
