### ISSUE TITLE
Unable to add team slug as wildcard domain on vercel dashbaord.

### ISSUE THREAD

**Issue by flashlog** [vercel/platforms#149]
Hi, 
According to the documentation:
```
You can also use wildcard subdomains on .vercel.app links that are associated with your Vercel team slug in this case, our team slug is "platformize", thus *.platformize.vercel.app works. Do note that you'll still need to add "*.platformize.vercel.app" as a wildcard domain on your Vercel dashboard.
```

When I try to add `*.TEAM_SLUG.vercel.app`, it throws an error:
```
Error:"USERNAME" does not have access to "*.TEAM_SLUG.vercel.app" domains.
```

Is there a way to resolve this?

**Comment by gregonarash** [comment]
@flashlog 

I was getting similar error, when I was trying to use `project name` instead of the `team name` in the slug.

**Comment by HialeahLiam** [comment]
Did you guys end up figuring out how to map subdomains when using the default Vercel generated domain?
