### ISSUE TITLE
Bump to Next.js v13

### ISSUE THREAD

**Issue by slavakurilyak** [vercel/platforms#159]
It would be great to see this template use the new `app/` directory instead of pages (Ex: `$ npx create-next-app@latest --experimental-app`) and turbopack (Ex: `$ next dev --turbo`) available in Next.js v13

**Comment by ehowey** [comment]
I second that - I think the new app directory and layouts will actually make this platforms template a lot more powerful!

**Comment by steven-tey** [comment]
Heck yeah!! Completely agree with you guys, gonna take a stab at this tomorrow! 🙈

**Comment by steven-tey** [comment]
[x] Upgrade to Next.js 13: https://github.com/vercel/platforms/pull/160 <picture data-single-emoji=":done:" title=":done:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..hb07ZfN4zNsudAsV.UKue4qoPB7_weAYmSJXPwWxi0kouNX8pZV_Q7fa6fQKqwz7WPwVW6wFmYuq7h50hjH11RsaUZtinl7asJoJJLoNPlNENZA5ZcSiID9vuOvryAdkWVww.jYi6Sd0zNmW_0VnPNTtB7w" alt=":done:" align="absmiddle"></picture> <picture data-single-emoji=":checked:" title=":checked:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..qLL2-2Bniik-apYg.Jf0OapPwmEhW8F_KHC95IlHmbwZDb-lq1dzQ1GrILbv-mqGw_udQGM3_PMJ_9e_CprYSjggZpEWGATPM-4Q0GWIVQTC4XWMg4iMFHmNFL1jgWGa5xdKfUH7S2Q.U9-dtBaSBaPONdgu1j6wKg" alt=":checked:" align="absmiddle"></picture> 
[ ] Migrate to `/app` folder

**Comment by Rieranthony** [comment]
Any update on that guys? Would be nice to see some exemples now that Next13 app router is quite stable 👯

**Comment by steven-tey** [comment]
@Rieranthony here's the latest PR for App Router migration: https://github.com/vercel/platforms/pull/221

**Comment by steven-tey** [comment]
The Platforms Starter Kit is now fully on the App Router 🥹

https://github.com/vercel/platforms/assets/28986134/2b0aa7b3-ffa8-4995-9e1f-cf128f57d007
