### ISSUE TITLE
Client side error on rendering certain tweets

### ISSUE THREAD

**Issue by kasem-sm** [vercel/platforms#162]
Hi there,
I just mentioned one of my tweet when I was trying the demo but got this error,
![image](https://user-images.githubusercontent.com/83884225/200187077-792cc424-338e-4bfe-84b9-29b7de62def5.png)

Most probably it's a JSON parsing issue but if the vercel team can look into this, it would be great. Meanwhile I'm also debugging the same.

For reference, the tweet was : https://twitter.com/KasemSM_/status/1578200759732436993 and the post is https://kasem.vercel.pub/cl9zrxcb7028408l6sbxz8b79.

**Comment by steven-tey** [comment]
Hey Kasem! The issue seems to have been resolved now so I'm going to go ahead and close this issue. LMK if you run into any other issues in the future!

![CleanShot 2022-11-18 at 17 40 30](https://user-images.githubusercontent.com/28986134/202820908-3892621d-eb68-4f82-aa1a-a9178e6febe5.png)
