### ISSUE TITLE
Middleware causing router.query to be empty

### ISSUE THREAD

**Issue by lechim** [vercel/platforms#163]
The initial render on a dynamic route through middleware results in an empty router.query object, but if I client side navigate to the dynamic route the router.query is correctly populated. When I remove middleware.ts the page work as expected and router.query is also populated. Seems to me there is a bug in the middleware in next 13, next 12 is still working as expected.

**Comment by sinclairnick** [comment]
I'm also getting this behaviour. Interestingly, when adding a `getStaticProps` to the page, the router then becomes populated

**Comment by lechim** [comment]
vercel/next.js#42463

**Comment by lechim** [comment]
vercel/next.js#42463
