### ISSUE TITLE
Custom domains

### ISSUE THREAD

**Issue by FrancocDev** [vercel/platforms#170]
Hi, I'm trying to make a project with platforms, but I receive a 403 (domain.tld is already owned by another team.Click here to request access.) every time I add a domain. 
The env variables for custom domains (Auth token and the project ID) are setted and re-deployed it but still the same issue.
Thanks in advance.

**Comment by ramnavan** [comment]
I'm facing the same error as @FrancocDev . @FrancocDev  - did you ever resolve this?

**Comment by ramnavan** [comment]
@FrancocDev - I think I figured it out. Make sure AUTH_BEARER_TOKEN env is set.

**Comment by bomjastik** [comment]
In my case, I was able to fix it by also adding an empty TEAM_ID_VERCEL to Environment Variables on Vercel

**Comment by steven-tey** [comment]
Sorry about the unclear instructions – but we've updated all the required env vars here: https://github.com/vercel/platforms/blob/main/.env.example

Closing this issue for now!
