### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by Spiteless** [vercel/platforms#173]
I've been trying to fork and play with this repo and have ran into an issue with deployment. Application runs properly locally. Originally I thought I was missing some steps to get it up and running, but some of the deploys listed by Vercel Bot are also failing the same way mine did.

#### Description
Some sites deployed by vercel bot in comment section provide "Application error: a client-side exception has occurred (see the browser console for more information)."

#### Screenshots
![image](https://user-images.githubusercontent.com/5898009/204160811-b2ce4a41-39fb-4df1-b32f-97d6aa6ab946.png)
![image](https://user-images.githubusercontent.com/5898009/204160824-b1313fab-f163-483f-b3b2-b1f1ff54684a.png)

#### To Reproduce
Click through the list of sites deployed by the vercel comment bot:
* https://init.vercel.pub/
* https://blogging-platform-vercel-labs.vercel.app/
* https://support-subdomain.vercel.pub/
* https://blogging-platform-git-main-vercel-labs.vercel.app/

The links only display the application error on first load. On 2nd load they return 404.

I'm not knowledgable enough to understand what's going on here.

**Comment by mohit2530** [comment]
Does anyone have a solution for this. We are also blocked by this same issue.

**Comment by bfourgeaud** [comment]
Something in your middleware matcher could be the problem. I had the same error, and is was in fact my matcher that matched some files it shouldn't.
Changing my matcher to this solved my problem :  
```
export const config = {
  matcher: ["/((?!api|_next/static|_next/image|.*svg|.*ico|.*png|.*js).*)"],
}
```

It matches also all .svg, .ico, .png and .js files in my `public/` folder

**Comment by Spiteless** [comment]
Chiming back in here to say that I switched to the above matcher and it didn't resolve this issue for me.

**Comment by prodkt** [comment]
Still happening today. This is faulty and from the look of everyone else left with questions unanswered this is no longer supported.

**Comment by steven-tey** [comment]
Hey y'all! Apologies for the late reply here! I just upgraded `next` to the latest version and it seems to have fixed this issue. Can you guys confirm?

**Comment by steven-tey** [comment]
Closing this since we've migrated to the App Router as per https://github.com/vercel/platforms/pull/221 and this should be fixed now!
