### ISSUE TITLE
After login not redirecting to homepage

### ISSUE THREAD

**Issue by PandiyanCool** [vercel/platforms#176]
I tried login in from http://app.localhost:3000/login
After login (with GitHub flow)

The page is again redirecting to http://app.localhost:3000/login

After I log in, If I visit http://app.localhost:3000/ manually in a new tab it is redirecting properly in the browser.

Do we need to update anything in middleware to handle this redirection?

**Comment by steven-tey** [comment]
Closing this since we've migrated to the App Router as per #221 and this should be fixed now!
