### ISSUE TITLE
revalidate blog page failed.

### ISSUE THREAD

**Issue by EryouHao** [vercel/platforms#177]
error info is reason: write EPROTO 139978634581952:error:1408F10B:SSL routines:ssl3_get_record:wrong version number.

Does anyone know why this is? cc @steven-tey 

Some times the update will be successful, other times it will report this error

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/17328747/208295747-f9d9b9fb-9e1b-46cb-8f30-c8372b7f467a.png">

**Comment by steven-tey** [comment]
Hey @EryouHao! Are you still facing this issue? If so can you try upgrading `next` to the latest version with `npm i next@latest` and see if the bug is still there?

**Comment by steven-tey** [comment]
Closing this since we're now using [`revalidateTag`](https://nextjs.org/docs/app/api-reference/functions/revalidateTag) for revalidating pages :) 

E.g.: https://github.com/vercel/platforms/blob/main/lib/actions.ts#L48-L50
