### ISSUE TITLE
Refactoring to beta app directory breaks client-side pushState navigation (prod only, works fine in dev)

### ISSUE THREAD

**Issue by nicksergeant** [vercel/platforms#178]
I'm working on refactoring my multi-tenant/platform code to the new app directory and everything seems to be working fine except for client-side `pushState` navigation in production. Locally the client-side nav is happening via `pushState`, but once deployed to production, navigations result in full page loads.

Here's a test repo: https://github.com/nicksergeant/next-13-spa-push-state-platforms

The relevant middleware code (simplified): https://github.com/nicksergeant/next-13-spa-push-state-platforms/blob/abb3bde1213840a3f7d8d2a4ecbaf2d4c00d4e62/middleware.ts#L7-L18

When visiting a non-middleware-caught route, pushState navigation works fine between the routes: https://next-13-spa-push-state.vercel.app/sites/foo (use the nav group `Nav links to a base path of /sites/foo:`)

But when hosting on a custom domain mapping to `/app/sites/foo` via the middleware, the routes all still load fine but client-side pushNav is broken, so every route nav results in a full page load: https://foo.flxwebsites.com/ (use the nav group `Nav links to a base path of /:`)

I tried looking through https://github.com/vercel/platforms/pull/161 to see if I'm missing some configuration change but I don't see anything...

**Comment by nicksergeant** [comment]
This seems to also be broken for the deployed version of https://github.com/vercel/platforms/pull/181: https://demo.vercel.pub/ (navigate from there to https://demo.vercel.pub/150m-series-d via link)

**Comment by steven-tey** [comment]
Ahh yes, there is a bug with `next/link` prefetch that we're looking into rn cc: @timneutkens @ijjk

**Comment by steven-tey** [comment]
This has since been fixed as per #221 :)
