### ISSUE TITLE
Getting a 404 on every homepage?!

### ISSUE THREAD

**Issue by Diogovski** [vercel/platforms#179]
Hi, idk why, but every page on the app gets an 404, except pages like http://app.localhost:3000/settings or the login, it works, but if i go to the normal page  http://app.localhost:3000/ it throws a 404 , localhost:3000 throws 404 ...
I am using t3 stack with this so i can use trpc...
Here's my repo https://github.com/Diogovski/teste

**Comment by RioChndr** [comment]
i found this problem too. Is vercel leave this template ?
