### ISSUE TITLE
Couldn't resolve dependencies related to Next@13

### ISSUE THREAD

**Issue by TaylorHo** [vercel/platforms#180]
Getting the source code from the master branch I'm not able to install the dependencies.

Every time it's throwing npm `ERESOLVE` error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: next-plausible@3.1.4
npm ERR! Found: next@13.0.4
npm ERR! node_modules/next
npm ERR!   next@"^13.0.4" from the root project
npm ERR!   peer next@"^12.2.5 || ^13" from next-auth@4.17.0
npm ERR!   node_modules/next-auth
npm ERR!     next-auth@"^4.17.0" from the root project
npm ERR!     peer next-auth@"^4.0.1" from @next-auth/prisma-adapter@1.0.1
npm ERR!     node_modules/@next-auth/prisma-adapter
npm ERR!       @next-auth/prisma-adapter@"^1.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^11.1.0 || ^12.0.0" from next-plausible@3.1.4
npm ERR! node_modules/next-plausible
npm ERR!   next-plausible@"^3.1.4" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: next@12.3.4
npm ERR! node_modules/next
npm ERR!   peer next@"^11.1.0 || ^12.0.0" from next-plausible@3.1.4
npm ERR!   node_modules/next-plausible
npm ERR!     next-plausible@"^3.1.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/user/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2023-01-06T18_18_32_597Z-debug-0.log
```

I think it can be related to #159, but I'm not sure.

Help is appreciated Thanks!

**Comment by TaylorHo** [comment]
Testing I've found that I can install dependencies with yarn.

Can it be something related to npm?

My npm version is 8.19.2
My node version is 18.12.1 (but the installation worked with yarn, so this must not be a node related error).

**Comment by SpBills** [comment]
Also happened here.

**Comment by SpBills** [comment]
@TaylorHo Could you try compiling? `yarn next build`

**Comment by ramnavan** [comment]
I'm facing the same problem as @TaylorHo. However, it works just fine on my local machine. It's in vercel deployment I see the dependency errors. Strange!

**Comment by SpBills** [comment]
@ramnavan I solved this by making it install with `npm i --legacy-peer-deps`

**Comment by ramnavan** [comment]
Thank you, @SpBills. That fixed it in Vercel. Do you have any idea why without `--legacy-peer-deps`, it'd work locally but failed in vercel?

**Comment by TaylorHo** [comment]
Today the package installation and building worked fine with **yarn**, **npm**, and **pnpm**.

Something changed?

**Comment by SpBills** [comment]
> Today the package installation and building worked fine with **yarn**, **npm**, and **pnpm**.
> 
> 
> 
> Something changed?

A large update happened yesterday... once I get back to my computer, I'll check it out.

**Comment by TaylorHo** [comment]
I've tested just now and the package installation is working as expected.

Thanks @SpBills 

Closing this issue.
