### ISSUE TITLE
Navigating back to root of custom domain page leads to a 404.

### ISSUE THREAD

**Issue by nicksergeant** [vercel/platforms#182]
I noticed this while writing up https://github.com/vercel/platforms/issues/178, but was hoping that it'd be fixed in the final merge of https://github.com/vercel/platforms/pull/181

If you navigate to https://demo.vercel.pub/ then click the link for "Announcing our $150M Series D" (https://demo.vercel.pub/150m-series-d), then use your browser's back button, you will get a 404.

Here's a GIF screencast of the bug:

![CleanShot 2023-01-08 at 13 54 32](https://user-images.githubusercontent.com/27332/211213798-3efeff16-1261-4453-8b47-daf3188aaa42.gif)

**Comment by nicksergeant** [comment]
I was able to manually fix/patch this in my test repo like [this](https://github.com/nicksergeant/next-13-spa-push-state-platforms/commit/1359452b76f5025ed5ecf3950df1e8254736ad65#diff-3c67eb27b539c61276d7c7cbcdbe15d4b37a6cbf58bf8bc12c1c4d7619c96d1cR15-R18) in the middleware:

```javascript
  // Next 13 sometimes appends 'index' to root paths after the page has loaded...
  let pathname = nextUrl.pathname;
  if (nextUrl.pathname === "/index") {
    pathname = "/";
  }
```

**Comment by steven-tey** [comment]
Hey Nick! Thanks for reporting this! This is a bug in the Next.js `/app` directory – the team is aware of it and are actively fixing it now!

**Comment by nicksergeant** [comment]
@steven-tey awesome to hear! Let me know if I can help beta test any future potential fixes for this, also 👍

**Comment by steven-tey** [comment]
Closing this since we've migrated to the App Router as per #221 and this should be fixed now!
