### ISSUE TITLE
Set app domain from a env variable

### ISSUE THREAD

**Issue by SharadKumar** [vercel/platforms#184]
Currently, the domain `vercel.pub` is hardcoded and magic string is sprinkled at numerous places in the code. Quite an effort since there are several sub-domains in use too: `demo` `platformize` `app` etc.

It would be really useful if this was set once so that DX of adopting and learning from this is improved.

**Comment by dragos199993** [comment]
hello 👋  @steven-tey can I help with a PR with this one? Thanks!

**Comment by steven-tey** [comment]
@dragos199993 sure! Feel free to PR – you can use a `NEXT_PUBLIC_ROOT_DOMAIN` URL to make sure it's accessible on the client side as well! :)

**Comment by steven-tey** [comment]
This has since been added to the Starter Kit as part of #221
