### ISSUE TITLE
Failed to collect page data for /_sites/[site]/[slug]

### ISSUE THREAD

**Issue by dedicatedcloud** [vercel/platforms#187]
I'm having no luck with this, I've never managed to have a successful build, this is my issue now

I follow the instructions

> Build error occurred
--
01:05:30.681 | Error: Failed to collect page data for /_sites/[site]/[slug]
01:05:30.682 | at /vercel/path0/node_modules/next/dist/build/utils.js:960:15 {
01:05:30.682 | type: 'Error'
01:05:30.682 | }
01:05:30.731 | Error: Command "npm run build" exited with 1

any help

**Comment by steven-tey** [comment]
Closing this since we've migrated to the App Router as per #221
