### ISSUE TITLE
Error in deploying

### ISSUE THREAD

**Issue by vashuyadavv** [vercel/platforms#188]
Hello all,

I recently created a web app with flask and i am trying to deploy it vercel. It perfectly works locally. But i can't seem to figure out why there is 404: Not_Found error when i am trying to make it live.

https://github.com/vashuyadavv/vashu-blog

Thanks in advance.

**Comment by steven-tey** [comment]
This starter kit uses Next.js for the framework and not Flask – closing this as unrelated for now!
