### ISSUE TITLE
Does this require a Pro account? 

### ISSUE THREAD

**Issue by bradparks** [vercel/platforms#191]
If it does, it should state it clearly at the top of the README, for both this and the supabase example.

**Comment by steven-tey** [comment]
No it doesn't, unless if you need unlimited custom domains: https://vercel.com/changelog/unlimited-custom-domains-for-all-pro-teams

Hobby accounts get 50 custom domains for free! :)

**Comment by bradparks** [comment]
Hmm... interesting! thanks - I will try again - much appreciated!
