### ISSUE TITLE
Finding sites with subdomain/custom domain

### ISSUE THREAD

**Issue by gaurishhs** [vercel/platforms#197]
Hi! thanks for this wonderful template, Can you please explain to me why we're finding sites with the subdomain `demo` [here](https://github.com/vercel/platforms/blob/main/pages/_sites/%5Bsite%5D/index.tsx#L131) or `platformize.co` [here](https://github.com/vercel/platforms/blob/main/pages/_sites/%5Bsite%5D/index.tsx#L143)

Thanks.

**Comment by steven-tey** [comment]
Closing this since we've migrated to the App Router as per #221 and this should be fixed now!
