### ISSUE TITLE
GET http://demo.localhost:3000/_next/data/development/index.json 404 (Not Found)

### ISSUE THREAD

**Issue by NTP-996** [vercel/platforms#199]
OS: Ubuntu22.04

I'm following https://vercel.com/guides/nextjs-multi-tenant-application#image-uploads-with-cloudinary
![Screenshot from 2023-02-11 20-59-07](https://user-images.githubusercontent.com/31298991/218263674-392f1a93-4b63-491e-bbd5-613ee3d1de63.png)

I don't see any error got reported in the terminal the image came from the browser console
The app.localhost:3000 work for now
Error in the demo.localhost:3000

**Comment by steven-tey** [comment]
Closing this since we've migrated to the App Router as per https://github.com/vercel/platforms/pull/221 and this should be fixed now!
