### ISSUE TITLE
SvelteKit Support

### ISSUE THREAD

**Issue by jerriclynsjohn** [vercel/platforms#208]
It will be great to have an example for SvelteKit, now that SvelteKit has support for [ISR on Vercel](https://kit.svelte.dev/docs/adapter-vercel#incremental-static-regeneration). SvelteKit already has support for middleware with its hooks. So implementation should be straightforward.

**Comment by steven-tey** [comment]
Closing this as it's related to https://github.com/vercel/platforms/discussions/189 – let's continue the discussion there! :)
