### ISSUE TITLE
Following the guide is kind of impossible

### ISSUE THREAD

**Issue by Venediktoff** [vercel/platforms#219]
You have a step for setting up the database and github auth etc, but you can't create a github auth key without providing the website address, which you don't get until you complete the setup proccess.

**Comment by christianlovescode** [comment]
If you're deploying from the template, just add a dummy placeholder for the github env vars. First deployment will likely fail, but you'll still get the vercel.app URL you can use to complete the github setup.

**Comment by steven-tey** [comment]
Planning to improve the guide as part of #221! Sorry about that 🙏

**Comment by Venediktoff** [comment]
@steven-tey never apologize for doing great stuff! Thank you for doing this! 

@christianlovescode Thank you, this works!

**Comment by steven-tey** [comment]
[The guide](https://vercel.com/guides/nextjs-multi-tenant-application) should be much better now!! We even have a way to [generate GH OAuth app in one-click](https://github-client-generator.vercel.app/), courtesy of @balazsorban44 😁 

Gonna go ahead and close this for now, but let me know if you're still running into issues – happy to reopen it! :)
