### ISSUE TITLE
Twitter Auth Essential Access error

### ISSUE THREAD

**Issue by kgrady13** [vercel/platforms#22]
I'm getting the following error. 

```
[next-auth][error][OAUTH_V1_GET_ACCESS_TOKEN_ERROR] 
https://next-auth.js.org/errors#oauth_v1_get_access_token_error undefined {
  statusCode: 403,
  data: '{"errors":[{"message":"You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve","code":453}]}\n'
}
```

I am following along with the [blog post](https://vercel.com/guides/nextjs-multi-tenant-application) but things do look different for me. For example, my Twitter dev dashboard does not have "enable 3-legged" option. Just the options in the screenshot below

![image](https://user-images.githubusercontent.com/58639463/150692344-28ae2171-16b2-42a2-8e80-42f9b7ec0577.png)

I can't even get the login button to prompt for Twitter oAuth without changing the callback URL in step 13 from the blog post suggestion of 'http://localhost:3000/api/auth/callback/twitter' (does not work) to 'http://app.localhost:3000/api/auth/callback/twitter' (prompts but get console error above)

If I follow the blog post exactly I get this

```
[next-auth][error][GET_AUTHORIZATION_URL_ERROR] 
https://next-auth.js.org/errors#get_authorization_url_error undefined {
  statusCode: 403,
  data: `<?xml version='1.0' encoding='UTF-8'?><errors><error code="415">Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>`
}
[next-auth][error][SIGNIN_OAUTH_ERROR] 
https://next-auth.js.org/errors#signin_oauth_error undefined {
  error: {
    statusCode: 403,
    data: `<?xml version='1.0' encoding='UTF-8'?><errors><error code="415">Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>`
  },
  provider: {
    id: 'twitter',
    name: 'Twitter (Legacy)',
    type: 'oauth',
    version: '1.0A',
    authorization: { url: 'https://api.twitter.com/oauth/authenticate', params: {} },
    accessTokenUrl: 'https://api.twitter.com/oauth/access_token',
    requestTokenUrl: 'https://api.twitter.com/oauth/request_token',
    profileUrl: 'https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true',
    profile: [Function: profile],
    clientId: 'xxxx-removed-xxxx',
    clientSecret: 'xxxx-removed-xxxx',
    signinUrl: 'http://app.localhost:3000/api/auth/signin/twitter',
    callbackUrl: 'http://app.localhost:3000/api/auth/callback/twitter'
  },
  message: undefined
}
```
Any help or suggestions is appreciated

**Comment by mattfwood** [comment]
I'm having the exact same issue. Not sure if you need a certain "level" of twitter dev account to do this, but the option doesn't show up at all and I'm stuck here while trying to set up.

**Comment by kgrady13** [comment]
> I'm having the exact same issue. Not sure if you need a certain "level" of Twitter dev account to do this, but the option doesn't show up at all and I'm stuck here while trying to set up.

I wonder if the Vercel team has a more advanced Twitter Developer Account and did not realize it. Lee Robinson made an issue (#23) asking if they should switch it to Github auth instead so that is promising.

**Comment by shugert** [comment]
Have you tried with 0Auth2? that will have access with your essential access:
`You currently have Essential access which includes access to Twitter API v2 endpoints only.`

**Comment by kgrady13** [comment]
> Have you tried with 0Auth2? that will have access with your essential access: `You currently have Essential access which includes access to Twitter API v2 endpoints only.`
> 
> Also, try with a secure url: https://app.yourdomainhere/api/auth/callback/twitter
> 
> don't forget to include both, 'http://localhost:3000/api/auth/callback/twitter' and 'https://app.localhost:3000/api/auth/callback/twitter' as well as your domain name.

Thanks for the suggestions. I have played around with the 0Auth2 option. Only using it, also having 1.0 turned on etc. No luck. As I get basically the same error:
```
[next-auth][error][OAUTH_V1_GET_ACCESS_TOKEN_ERROR] 
https://next-auth.js.org/errors#oauth_v1_get_access_token_error undefined {
  statusCode: 403,
  data: '{"errors":[{"message":"You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve","code":453}]}\n'
}
[next-auth][error][OAUTH_CALLBACK_ERROR] 
https://next-auth.js.org/errors#oauth_callback_error undefined {
  statusCode: 403,
  data: '{"errors":[{"message":"You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve","code":453}]}\n'
}
```
I also double-checked all the proper callback URL's were listed (even though they are not listed on the blog post).

I am assuming you were able to get it to work? I am curious if you had the same settings as me in the Twitter developer portal or if it looked like the blog post?

**Comment by steven-tey** [comment]
@kgrady13 I think you might be right – just checked and our project seems to have elevated access to Twitter API v2:
![CleanShot 2022-01-24 at 10 54 46](https://user-images.githubusercontent.com/28986134/150846057-be6537d8-8f06-4c16-b0e2-eadafc9086d8.png)

We'll be switching over to Github OAuth to keep things simple but if folks still prefer Twitter OAuth we'll try and find a way to make this work.

CC'ing @balazsorban44 who's the creator of `next-auth` who might be able to weigh in on this!

**Comment by Dax911** [comment]
I am also having this issue.

**Comment by cezarneaga** [comment]
i have elevated access but the calls are on v1 not v2.
```
[next-auth][error][GET_AUTHORIZATION_URL_ERROR]
https://next-auth.js.org/errors#get_authorization_url_error undefined {
  statusCode: 401,
  data: '{"errors":[{"code":32,"message":"Could not authenticate you."}]}'
}
[next-auth][error][SIGNIN_OAUTH_ERROR]
https://next-auth.js.org/errors#signin_oauth_error undefined {
  error: {
    statusCode: 401,
    data: '{"errors":[{"code":32,"message":"Could not authenticate you."}]}'
  },
  provider: {
    id: 'twitter',
    name: 'Twitter (Legacy)',
    type: 'oauth',
    version: '1.0A',
    authorization: { url: 'https://api.twitter.com/oauth/authenticate', params: {} },
    accessTokenUrl: 'https://api.twitter.com/oauth/access_token',
    requestTokenUrl: 'https://api.twitter.com/oauth/request_token',
    profileUrl: 'https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true',
    profile: [Function: profile],
    clientId: '...',
    clientSecret: '....',
    signinUrl: 'http://app.localhost:3000/api/auth/signin/twitter',
    callbackUrl: 'http://app.localhost:3000/api/auth/callback/twitter'
  },
  message: undefined
}
```

**Comment by leerob** [comment]
Hey there, sorry about this. There has been a number of issues with the Twitter API, and the number of steps to get it working, so we're going to switch to GitHub OAuth instead.

https://github.com/vercel/platforms/issues/23
