### ISSUE TITLE
Current Build & Guide Fail

### ISSUE THREAD

**Issue by perkail** [vercel/platforms#225]
The current build is failing, and the guide doesn't work, as I can't get anything to load locally or on Vercel. Does anyone know when this template might have a stable build?

**Comment by FredvanRijswijk** [comment]
```"next": "13.4.8"``` 

and 

```// rewrite root application to `/home` folder
  if (hostname === "localhost:3000" || hostname === process.env.NEXT_PUBLIC_ROOT_DOMAIN) {```

**Comment by perkail** [comment]
Thanks. This has been killing me.

**Comment by steven-tey** [comment]
Closing as a duplicate of #232
