### ISSUE TITLE
Switch from Twitter to GitHub OAuth

### ISSUE THREAD

**Issue by leerob** [vercel/platforms#23]
Overall, GitHub OAuth has a lot fewer steps to get set up than Twitter OAuth. I think this would help those trying to get the project set up and running locally. Plus, with next-auth, you can always switch to other providers if you want.

Thoughts?

**Comment by kgrady13** [comment]
Yes for me! I find Github auth easy to implement. All the best, Lee.

**Comment by GuidoOffermans** [comment]
Yes that sounds great! To set up up twitter took me a while. Thanks Lee :)

**Comment by amarpathak** [comment]
Hey can I pick this up ? I tried setting up twitter but wasn't able to, as github has easy steps I was able to setup github easily.

**Comment by steven-tey** [comment]
@amarpathak sounds good, feel free to start a PR and I'll review it + add the necessary env vars on the Vercel project and merge it! :)

**Comment by aaronmarkle** [comment]
Just to jump on the train here, an hour after getting this setup, Twitter suspended my newly created app/api access. Great to hear that Github will be suggested as the default.

**Comment by steven-tey** [comment]
@aaronmarkle Ahh sorry to hear that! Twitter auth can be a pain! Will try and get this switched over to Github auth ASAP! :)

**Comment by futantan** [comment]
How￼￼ about using Supabase instead of PlanetScale since it contains Authentication feature already.

**Comment by leerob** [comment]
We also like Supabase, but specifically for this starter kit we wanted to use Prisma. Supabase has their own JS client we would have used instead.

**Comment by steven-tey** [comment]
@cezarneaga kicked this off with #33! :)

**Comment by steven-tey** [comment]
Just merged #33 – it's in prod now! :)
