### ISSUE TITLE
Root Domain and Vercel project autodomain Redirecting to Vercel.com page

### ISSUE THREAD

**Issue by perkail** [vercel/platforms#236]
localhost and root domain are redirecting to https://vercel.com/blog/platforms-starter-kit

Check behavior here: https://yarndi.com or yarndi.vercel.app

**Comment by ericklg** [comment]
this is the end of the middleware.ts file where the redirect is located, with this change (I commented the redirect to the blog post and uncommented the rewrite to `/home` ) you will see the `/home` page in your app folder.
` // rewrite root application to `/home` folder
  if (
    hostname === "localhost:3000" ||
    hostname === process.env.NEXT_PUBLIC_ROOT_DOMAIN
  ) {
    return NextResponse.rewrite(new URL(`/home${path}`, req.url));
    // we're redirecting to the blog post for this demo, but you can change this to
    // rewrite to the /home folder if you want to use the home page (or whatever you wanna name it)
    // return NextResponse.redirect(
    //   "https://vercel.com/blog/platforms-starter-kit",
    // );
  }`
hope it helps.

**Comment by perkail** [comment]
Oh yeah. I see it now. I did go through the whole middleware.ts but it was late and I was fading...

**Comment by perkail** [comment]
Yeah this is confirmed so I'll close it. Maybe @steven-tey can annotate the guide. Seriously great job with this. We're all really stoked to build on top of this

**Comment by steven-tey** [comment]
@perkail good call, will add it to the guide! Thank you!
