### ISSUE TITLE
How to get BLOB_READ_WRITE_TOKEN ?

### ISSUE THREAD

**Issue by Skyminers** [vercel/platforms#242]
I follow this [guide](https://vercel.com/guides/nextjs-multi-tenant-application) but the link here lead me to 404 page.

> BLOB_READ_WRITE_TOKEN: [Follow the steps here](https://vercel.com/docs/storage/blob/quickstart) to provision a Vercel Blob instance. If you have already deployed the template, you can pull the env vars with the Vercel CLI by running vc env pull.

<img width="610" alt="image" src="https://github.com/vercel/platforms/assets/23115950/8ce5941c-2008-407f-9151-52d3f528a6a8">

**Comment by FredvanRijswijk** [comment]
DM @steven-tey on twitter.

**Comment by VictorCalderon** [comment]
Patiently waiting for my response too @steven-tey <3. He must be very busy trying to get them all...

**Comment by steven-tey** [comment]
Hey y'all! If I haven't replied to you already – can you send me your Vercel user ID (you can find that [here](http://vercel.com/account)) + the team ID (can be found on the team settings page) if you're using it on a team?

**Comment by Skyminers** [comment]
Hello, I have send my Vercel user ID to you. But I did not use it on a team. Does this have to be used on team?

**Comment by Skyminers** [comment]
Thant you! I got reply on twitter.
