### ISSUE TITLE
Extremely slow

### ISSUE THREAD

**Issue by parweb** [vercel/platforms#256]
I just install this app on local and run it with yarn dev
everything works

I didn't change anything appart from env variables

but when I navigate between pages it's extremely slow like 10-20s before render 
I on a mac from 2019

2,8 GHz Intel Core i7 quatre cœurs
16 Go 2133 MHz LPDDR3

**Comment by TatisLois** [comment]
Similar experience, not as slow but I noticed the delay and not sure if this is expected?

**Comment by sync-adm** [comment]
Did you try to build and check if it occurs when on builded site? I think it's happening because for each site you have, next js on dev tries to get all pages data and paths on each navigation. It's the default behavior when development AFAIK.

**Comment by steven-tey** [comment]
This is probably due to the `lucide-react` package which exports a ton of modules that slows up local dev compilation time!

The Next.js team is aware of it and will be fixing it soon!

**Comment by steven-tey** [comment]
Should be fixed now <picture data-single-emoji=":cele-cry:" title=":cele-cry:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/cele-cry/0b3863f465db725f.png" alt=":cele-cry:" align="absmiddle"></picture>
