### ISSUE TITLE
Vercel Blob Access

### ISSUE THREAD

**Issue by KalilAziz** [vercel/platforms#265]
Good morning. I would like to have access to Vercel Blob. I sent an invite but still not successful. I know you asked me to contact you on twitter, but I can't send you a message because of the verification badge. Could you please give me access to the resource? I would like to ask if even in beta it can be used for production?

**Comment by vivek7405** [comment]
Even I would like the access to Vercel Blob on my Vercel account vivek7405@gmail.com!
I have already sent a DM on Twitter to @steven-tey asking for access.
Thanks in advance!

**Comment by TatisLois** [comment]
Same!

**Comment by steven-tey** [comment]
Please sign up with this form for the Vercel Blob beta: https://vercel.fyi/blob-beta

**Comment by brinnaebent** [comment]
Hi @steven-tey, is there any way to get bumped up on the waitlist? I have been on the waitlist for Vercel Blob for weeks and haven't seen any movement. Thank you!
