### ISSUE TITLE
[next-auth][warn][EXPERIMENTAL_API]

### ISSUE THREAD

**Issue by naifblf** [vercel/platforms#266]
Hello, when I visit any website that I have created, I get a 404 message, and this message is printed in the console :

event compiled client and server successfully in 3.7s (7298 modules)
[next-auth][warn][EXPERIMENTAL_API]
`getServerSession` is used in a React Server Component.
https://next-auth.js.org/configuration/nextjs#getServerSession}
https://next-auth.js.org/warnings#EXPERIMENTAL_API

Do you have an idea of a solution to this problem or can you help me ?

Thank you

**Comment by steven-tey** [comment]
It's a warning for now – you can safely ignore it! Once RSC + next-auth compatibility is stable it'll be removeed!
