### ISSUE TITLE
every time I deploy the platform shows an error

### ISSUE THREAD

**Issue by MohammadTaseenKhan** [vercel/platforms#268]
![image](https://github.com/vercel/platforms/assets/85288261/6d939e48-37c3-4b0a-b5b2-1b813b859d83)

**Comment by MohammadTaseenKhan** [comment]
[https://app.taseenblog.ml/](https://app.taseenblog.ml/)

**Comment by vikim540** [comment]
I feel the same way! I have confidence.

**Comment by steven-tey** [comment]
Sorry, what do you mean by an error? I don't see any errors here – this is the intended behavior when you visit the root domain. Here's the code that does that: https://github.com/vercel/platforms/blob/main/middleware.ts#L49-L55

**Comment by piyushhanchate** [comment]
@steven-tey  how does one actually go to the app page, then?

**Comment by Articologist** [comment]
Serious?

**Comment by leerob** [comment]
Hey there, it's not clear what the error is here. If you are still seeing this, please open a new issue with a reproduction.
