### ISSUE TITLE
Error when deploying

### ISSUE THREAD

**Issue by gomide** [vercel/platforms#274]
Hello, when deploying using the project it is showing the following error, even without making any changes to the code

Erro: O Edge Function "middleware" está referenciando módulos não suportados:
--
09:55:22.858 | - próximo: stream, fs, url

**Comment by JonCatmull** [comment]
Hi @gomide, I'm facing the exact same issue. Did you manage to resolve this?

**Comment by leerob** [comment]
Closing as stale, but let me know if you're still seeing this issue.

**Comment by JonCatmull** [comment]
Hi I resolved the issue for myself. It is caused when the framework preset in the project settings isn't configured correctly. I used the platform starter kit and even when installing using the 1 click deploy from https://vercel.com/templates/next.js/platforms-starter-kit it defaults to "other" not "Next.js". If possible the starter kit should be updated to have this setting applied automatically to avoid people having the same issues.
