### ISSUE TITLE
Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times

### ISSUE THREAD

**Issue by deewebgr** [vercel/platforms#276]
Getting this when trying to create a new site.

**Comment by steven-tey** [comment]
This is not related to Platforms but instead related to <FocusTrap/>: https://github.com/focus-trap/focus-trap/blob/master/README.md#error-your-focus-trap-must-have-at-least-one-container-with-at-least-one-tabbable-node-in-it-at-all-times
