### ISSUE TITLE
Using other providers than just Github

### ISSUE THREAD

**Issue by berriosa13** [vercel/platforms#277]
Has anyone gotten any other next-auth providers to work with this besides github? I have been trying to setup google but when I try to add the same callback urls as outlined in the start up guide, but google won't allow .app.localhost:300 redirects. I have my NEXTAUTH_URL env variable set as http://app.localhost:3000. Github accepts the redirect urls without any issues, but google will not. 

<img width="514" alt="image" src="https://github.com/vercel/platforms/assets/54926487/df935446-537c-44a8-9a6f-0b9ac8b351de">

**Comment by Jace996** [comment]
@berriosa13 you may try to deploy to vercel with real domain first and try again. Google will not accept localhost url unless you have a localhost google service for testing.

**Comment by berriosa13** [comment]
> 

This makes sense. Going to go this route or maybe even try to implement something like ngrok.
