### ISSUE TITLE
www subdomain not working 

### ISSUE THREAD

**Issue by ikramhasan** [vercel/platforms#278]
First of all, thank you for this amazing template. We needed to implement exactly this feature. I cannot express how much time you have saved us.

**The issue:**
Hi, I followed the guide and skipped redirect from www subdomains as mentioned. But as a result, if users put www in front of the name of the website, it doesn't load at all. 

So,
✔️https://onetapfolio.com ➡️ works fine 
❌https://www.onetapfolio.com ➡️ doesn't work

But we need to support www subdomain as our users are getting very confused. 
Here's our middleware which has been modified slightly to support our other use cases. 

```typescript
import { getToken } from "next-auth/jwt"
import { withAuth } from "next-auth/middleware"
import { NextResponse } from "next/server"

export default withAuth(
  async function middleware(req) {
    const url = req.nextUrl;

    // Get hostname of request (e.g. demo.vercel.pub, demo.localhost:3000)
    const hostname = req.headers
      .get("host")!
      .replace(".localhost:3000", `.${process.env.NEXT_PUBLIC_ROOT_DOMAIN}`);

    // Get the pathname of the request (e.g. /, /about, /blog/first-post)
    const path = url.pathname;

    if (hostname.startsWith('onetapfolio.com') || hostname.startsWith('localhost:3000')) {
      const token = await getToken({ req })
      const isAuth = !!token
      const isAuthPage =
        req.nextUrl.pathname === "/" ||
        req.nextUrl.pathname.startsWith("/login") ||
        req.nextUrl.pathname.startsWith("/register")

      if (isAuthPage) {
        if (isAuth) {
          return NextResponse.redirect(new URL("/dashboard", req.url))
        }

        return null
      }

      if (!isAuth) {
        let from = req.nextUrl.pathname;
        if (req.nextUrl.search) {
          from += req.nextUrl.search;
        }

        return NextResponse.redirect(
          new URL(`/login?from=${encodeURIComponent(from)}`, req.url)
        );
      }
    } else {
      return NextResponse.rewrite(new URL(`/u/${hostname}`, req.url));
    }


  },
  {
    callbacks: {
      async authorized() {
        // This is a work-around for handling redirect on auth pages.
        // We return true here so that the middleware function above
        // is always called.
        return true
      },
    },
  }
)

export const config = {
  matcher: ["/((?!api/|_next/|_static/|_vercel|[\\w-]+\\.\\w+).*)",],
}
``` 

**What we need:** 
Now, can you suggest what I need to change to support www subdomain? I want it to navigate to our home page. Also, I think it would be great if you add this to the guide as I personally think that every site should support this subdomain. 

Thank you for taking your time to read my question.

**Comment by oryan** [comment]
In your DNS settings with your registrar forward the www to the naked domain.

**Comment by steven-tey** [comment]
@ikramhasan great point! I just added a way to do this: https://vercel.com/guides/nextjs-multi-tenant-application?__vercel_draft=1#2.-allow-adding-and-redirecting-www.-subdomains-to-apex-domain
