### ISSUE TITLE
Failed to compile: Module not found: Can't resolve '/platforms/node_modules/lucide-react/dist/cjs/icons/alert-circle'

### ISSUE THREAD

**Issue by jpvalery** [vercel/platforms#281]
Hey there!

Building my first platform project thanks to this starter but running into this error:

![image](https://github.com/vercel/platforms/assets/4112343/7a01bc52-c0f5-42bb-b7f5-92ff669d65c3)

```
./node_modules/lucide-react/dist/cjs/lucide-react.js:2:0
Module not found: Can't resolve '/platforms/node_modules/lucide-react/dist/cjs/icons/alert-circle'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./components/form/domain-configuration.tsx
```

I can always remove that particular import but would like to ensure that this isn't a larger issue

**Comment by jpvalery** [comment]
Tried using different icons but it didn't work.

Ran 
```
yarn upgrade lucide-react@latest
```

And that did the trick

**Comment by JanKups** [comment]
Looks like a fix is coming: https://github.com/vercel/next.js/pull/53697

You can use this in the meantime:
`"lucide-react": "0.263.1"`
