### ISSUE TITLE
Suggestion: Add avatar.vercel.sh into the next.config.js file

### ISSUE THREAD

**Issue by jared-luke** [vercel/platforms#288]
Hi,

Love everything about this project. I ended up spinning it up locally, and I switched the Github AuthProvider out for the Email AuthProvider. 

By doing this I uncovered an issue with the code found here: https://github.com/vercel/platforms/blob/main/components/profile.tsx#L22

I believe it's a simple fix by adding the `avatar.vercel.sh` into the `next.config.js` file.

Thanks, and sorry if the format of this message is incorrect. First time posting on an open source project!
Cheers

**Comment by steven-tey** [comment]
Good point, thank you!
