### ISSUE TITLE
Branch preview

### ISSUE THREAD

**Issue by adamchipperfield** [vercel/platforms#294]
Is it possible to get this working with branch preview URLs? So **sub-domain**.project-git-feature-branch.vercel.app, where sub-domain is what the user has set as their subdomain.

If I try this I get SSL issues, as if Vercel can't handle wildcard subdomains on branch previews.

**Comment by sharshi** [comment]
I get 404's on all preview links - not sure what the correct setup besides enabling wildcard domains. I feel like there might be some sort of conflict because of the `NEXT_PUBLIC_ROOT_DOMAIN` setting being different to `vercel.app`.

**Comment by lukasburns** [comment]
Any luck with this so far?

**Comment by goussaka-salah** [comment]
is there any update regarding this

**Comment by joshualinog** [comment]
# **$100/month is the answer?**

> Preview Deployment Suffixes

This seems ridiculous to be the solution to a problem related to a 404 error on preview urls.
![image](https://github.com/user-attachments/assets/383014a1-df2e-4b82-8740-4a9584bb4693)

**Comment by iljapanic** [comment]
Unfortunately, even as a paying organization with a Pro plan, we would still need to pay an additional $100/moth just to get preview URLs working on Vercel in a multi-tenant setup.
