### ISSUE TITLE
middleware file strips search params query params

### ISSUE THREAD

**Issue by jphyqr** [vercel/platforms#297]
the middleware rewrite strips off your search params. 

`    return NextResponse.rewrite(
      new URL(`/app${path === "/" ? "" : path}**?${url.searchParams}**`, req.url),
    );
`

i added this so that I can have search params in my pages.tsx files.  

dunno if any other issues with this, but something to look for

**Comment by MohJaber93** [comment]
I am facing this issue too, it works after adding this `?${url.searchParams}` to the URL

**Comment by steven-tey** [comment]
Good point! Just added this which should fix this: https://github.com/vercel/platforms/blob/main/middleware.ts#L27-L29
