### ISSUE TITLE
Duplicate content on [domain] path for subdomain+customDomain?

### ISSUE THREAD

**Issue by zevi-wiply** [vercel/platforms#302]
### Discussed in https://github.com/vercel/platforms/discussions/300

<div type='discussions-op-text'>

<sup>Originally posted by **zevi-wiply** August 22, 2023</sup>
If I'm understanding correctly, the generateStaticParams in [domain]/layout.tsx returns as paths all subdomains and all non-null customDomains, and then the page fetches the site data based on unique subdomain/customDomain, etc..
<br/>
This would mean though that there are two separate static pages, one on the subdomain path and one of the customDomain path that both fetch the exact same site data.
I assume it's implemented this way so that we don't need to do any queries in middleware, but isn't it bad practice and a waste of storage having two different sites displaying the same content or am I missing something here?
<br/>
Any suggestions as to how I could implement custom subdomains and custom domains without generating two separate static pages with the same content?</div>

**Comment by steven-tey** [comment]
Hey @zevi-wiply! There are several ways you can avoid/improve this:

1. Redirect subdomain to custom domain if exists: We actually have a section of the code that lets you do that: https://github.com/vercel/platforms/blob/main/app/%5Bdomain%5D/layout.tsx#L105-L112
2. Setting a canonical URL that points to the custom domain if it exists: https://github.com/vercel/platforms/blob/main/app/%5Bdomain%5D/layout.tsx#L50-L56

**Comment by tomgreeEn** [comment]
How about this as a "yes, and", to prevent duplicate paths ever being selected for pre-render:

 ```
const allPaths = allSites
    .flatMap(({ subdomain, customDomain }) => [
      subdomain &&
        !customDomain /*   <-----  Only include subdomains where there's no customDomain    */ && {  
          domain: `${subdomain}.${process.env.NEXT_PUBLIC_ROOT_DOMAIN}`,
        },
      customDomain && {
        domain: customDomain,
      },
    ])
    .filter(Boolean);
```
