### ISSUE TITLE
Images Not Rendering (Blog Page, Blog Post, Logo)

### ISSUE THREAD

**Issue by lukketsvane** [vercel/platforms#303]
**Body:**
I've cloned and deployed the Platforms Starter Kit, but images (blog page, blog post, logo) aren't rendering. I believe this might be related to "blob."

- **Project:** Platforms Starter Kit
- **Issue:** Images not rendering
- **Suspected Cause:** Blob (is it in beta, and do I need access?)
- **Attempted Solutions:** Checked image paths, consulted documentation

If blob is in beta and access is required, please advise on how to request it. Any other pointers or solutions would also be greatly appreciated.

**Comment by Neosprings** [comment]
@lukketsvane Did you resolve this issue? I'm having the same problem with blog main banner, profile main banner, but anything in novel editor is displaying fine.
