### ISSUE TITLE
This repo yields no success. Jumping to the latest pull request from repo janpio/platforms works great

### ISSUE THREAD

**Issue by prodkt** [vercel/platforms#308]
Found in the pull requests. Simply over-riding the pull from vercel/platforms with janpio/platforms pnpm i && pnpm dev all works flawlessly. Something in this main branch causing all the pain. Just a heads up!

**Comment by fanksin** [comment]
@prodkt it's next-auth package that is not fully compatible with latest nextjs 13 canary and throwing error while installing packages. 

if you use --legacy-peer-deps flags while installing packages, like: npm i --legacy-peer-deps 
then it works.

**Comment by jesper-bylund** [comment]
Why don't we update the package to contain a non-breaking combination of packages?

**Comment by steven-tey** [comment]
Sorry about this – this should be fixed now! 🙏
