### ISSUE TITLE
If hobby account and trying Platforms V2 with no TEAM_ID_VERCEL what can I put in?

### ISSUE THREAD

**Issue by zkeller23** [vercel/platforms#317]
Is this a missed requirement to have TEAM_ID_VERCEL=

I'm new to vercel and wanting to try this.
When I placed "-" for that I got 404 after installation.
How can I have working setup without teams if it is not required?

**Comment by MalikAbdCom** [comment]
i personally just leave it empty at the moment

**Comment by zkeller23** [comment]
You are not able to leave it empty so I put a dash. Then I was able take it out completed and redeployed and still 404 error.

**Comment by zaggy00** [comment]
Did you resolve this? I'm also using a hobby account and it's asking me for a team ID. I'm going to go with a 2 week trial and then see if there's a resolution.

**Comment by steven-tey** [comment]
good point, should've clarified – you can leave that env var out if you are not using a team! just updated the code as well: https://github.com/vercel/platforms/commit/b6f2a5e9049c450e75bd18ff0ca90fc3a72d1f50 🙏
