### ISSUE TITLE
Vercel Blob

### ISSUE THREAD

**Issue by growthUx** [vercel/platforms#322]
Hi there, I just dropped the API key of Vercel Blob Storage and deployed. Unfortunately the image doesn't seem to map or at least the reference to the image doesn't work. Here's an example implementation: https://work.virtualpro.ph. Any way that Vercel Blob Storage is supported out of the box? I know it's in Beta, but would love to get insights/help.

**Comment by marketgrowth-vrx** [comment]
For some reason this got fixed. Installed next canary and update next.config image to the blob.
