### ISSUE TITLE
Google Auth Invalid Redirect Issue with app Subdomain Prefix

### ISSUE THREAD

**Issue by lexsemenenko** [vercel/platforms#329]
While the current authentication callback URL setup works well for GitHub login, I encounter problems when trying to set up a Google login. For GitHub, the following callback URLs are functional:

http://app.localhost:3000/api/auth/callback/github
https://app.<YOURDOMAIN.COM>/api/auth/callback/github

However, Google login setup does not permit the use of a callback with a subdomain prefix.

Issue:
When attempting to add Authorized Redirect URIs on the Google Developer Console, the following error messages are displayed:

Invalid Redirect: must end with a public top-level domain (such as .com or .org).
Invalid Redirect: must use a domain that is a valid top private domain.

Expected Behavior:
I expected to be able to use a callback URL with a subdomain prefix (like app) as it is functional and accepted for GitHub authentication.

Please provide a solution to make Google login work. Or please guide if I am missing something. 

[Link to Google Client Settings](https://console.cloud.google.com/apis/credentials/)
Screenshot attached. 
![CleanShot 2023-10-04 at 16 35 34@2x](https://github.com/vercel/platforms/assets/3987006/bacefbd2-67e6-439a-a27d-2606e0a6b690)

**Comment by peiris** [comment]
@lexsemenenko were you able to find a solution?

**Comment by steven-tey** [comment]
Hey @lexsemenenko! This is a known limitation with Google OAuth – just added a section in the guide on how to fix this: https://vercel.com/guides/nextjs-multi-tenant-application#4.-sign-in-with-google-limitations-in-localhost

![CleanShot 2023-11-14 at 11 18 41](https://github.com/vercel/platforms/assets/28986134/6d144bd1-2216-4f10-a2d2-b3786d91faa5)

**Comment by wispyco** [comment]
I am not sure I understand the final solution.

Am I to run `pnpm dev --port 8888`

Which makes no sense it's just changes the port number and then I have to reflect that in my app.

Do I forward localhost:8888 to app.localhost:3000

I tried with nginx didn't work.

What am I missing here, the instructions seem simple, yet I am lost.

All the code has the app.localhost:3000 hardcoded throughout, how is change the NEXTAUTH_URL going to work, especially with the middleware rewriting the `app.urls`

😕

**Comment by wispyco** [comment]
OH, so there must be something setup that I am unaware of. But if I visit 

http://localhost:8888/login

I get a page not found so something is working sorta.

any idea as to what will fix that.

**Comment by wispyco** [comment]
Ok so I added the correct oauthUrl but get redirected to this

http://localhost:8888/login?callbackUrl=http%3A%2F%2Flocalhost%3A8888&error=OAuthCallback

Not sure what it's saying there is an error in the OAuthCallback

**Comment by wispyco** [comment]
This is my GoogleProvider

```
GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID as string,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET as string,
      authorization: { params: { scope: "openid email profile" } },

    })
```

And I added the scopes to my oauth consent screen

**Comment by mavdotso** [comment]
> Hey @lexsemenenko! This is a known limitation with Google OAuth – just added a section in the guide on how to fix this: https://vercel.com/guides/nextjs-multi-tenant-application#4.-sign-in-with-google-limitations-in-localhost
> 
> ![CleanShot 2023-11-14 at 11 18 41](https://private-user-images.githubusercontent.com/28986134/282897934-6d144bd1-2216-4f10-a2d2-b3786d91faa5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDgzNzYsIm5iZiI6MTcwMzA0ODA3NiwicGF0aCI6Ii8yODk4NjEzNC8yODI4OTc5MzQtNmQxNDRiZDEtMjIxNi00ZjEwLWEyZDItYjM3ODZkOTFmYWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA0NTQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZmUxOTkyNTEwYzI2ZjMzNDQzZjFiOWI1Yjc4MDA4ZmIwY2M0YWI3OWFjOWRjOTcyMmNiYWE5NGY2ZmRlMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KLYYoeqQu1JgqEpvQshVr0MQb0cenBa3qdbIkTsbpDc)

This workaround doesn't seem to work anymore:
![CleanShot 2023-12-20 at 12 18 42@2x](https://github.com/vercel/platforms/assets/21265666/dce8b24c-f125-469b-8587-0876bf6469f0)

**Comment by trevorpfiz** [comment]
> I am not sure I understand the final solution.
> 
> Am I to run `pnpm dev --port 8888`
> 
> Which makes no sense it's just changes the port number and then I have to reflect that in my app.
> 
> Do I forward localhost:8888 to app.localhost:3000
> 
> I tried with nginx didn't work.
> 
> What am I missing here, the instructions seem simple, yet I am lost.
> 
> All the code has the app.localhost:3000 hardcoded throughout, how is change the NEXTAUTH_URL going to work, especially with the middleware rewriting the `app.urls`
> 
> 😕

I am not really understanding the `localhost:8888` solution as well. Any luck?

**Comment by stellarsite** [comment]
> > I am not sure I understand the final solution.
> > Am I to run `pnpm dev --port 8888`
> > Which makes no sense it's just changes the port number and then I have to reflect that in my app.
> > Do I forward localhost:8888 to app.localhost:3000
> > I tried with nginx didn't work.
> > What am I missing here, the instructions seem simple, yet I am lost.
> > All the code has the app.localhost:3000 hardcoded throughout, how is change the NEXTAUTH_URL going to work, especially with the middleware rewriting the `app.urls`
> > 😕
> 
> I am not really understanding the `localhost:8888` solution as well. Any luck? @wispyco

any luck?

**Comment by codyeisenbach** [comment]
Also having this problem, and like @wispyco I don't understand how such a simple solution could work when the middleware rewrites urls to start with "app.".

If someone could provide some insight it would be extremely appreciated

**Comment by mj-meyer** [comment]
For anyone that doesn't get the port 8888 thing. This is what I did to get it working:

You'll want to change this line: https://github.com/vercel/platforms/blob/29e20e790eaf17d4d5051c23a69636dce724c174/middleware.ts#L42

To include the 8888 hostname:
```javascript
  if (
    hostname == `app.${process.env.NEXT_PUBLIC_ROOT_DOMAIN}` ||
    hostname == 'localhost:8888'
  ) {
```

then in your `.env` you'll want to change the next auth url to `NEXTAUTH_URL="http://localhost:8888"
`

then you serve both ports 3000 `pnpm dev` and 8888 `pnpm dev --port 8888`

use http://localhost:8888/ to login. From there, clicking on any links within the app that contains `app.localhost` will open up localhost:3000 with no issue while any auth stuff happens on 8888.

it's not perfect, but it works.

**Comment by mworks-proj** [comment]
Hello, I managed to get this working but didn't want to go through the hassle of updating the ports and or changing any middleware functions.

Alternative solution: simply add both buttons to the login page. 

Add Auth Credentials to  env.local &  Vercel environment variables

```jsx
#Google OAuth 
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""

```

Make sure to separate the loading state of the buttons:

```jsx
const [loadingGoogle, setLoadingGoogle] = useState(false);
const [loadingGitHub, setLoadingGitHub] = useState(false);

```
Then add both buttons (depending on your auth, use the best branding suggested, this is for testing only):

```jsx

return (
  <>
    <!-- Google Login Button -->
    <button
      disabled={loadingGoogle}
      onClick={() => {
        setLoadingGoogle(true);
        signIn("google");
      }}
      className={`${
        loadingGoogle
          ? "cursor-not-allowed bg-stone-50 dark:bg-stone-800"
          : "bg-white hover:bg-stone-50 active:bg-stone-100 dark:bg-black dark:hover:border-white dark:hover:bg-black"
      } group my-2 flex h-10 w-full items-center justify-center space-x-2 rounded-md border border-stone-200 transition-colors duration-75 focus:outline-none dark:border-stone-700`}
    >
      {loadingGoogle ? (
        <LoadingDots color="#A8A29E" />
      ) : (
        <>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
            viewBox="0,0,256,256"
            width="24px"
            height="24px"
          >
            <g fill="#fa5252" fillRule="nonzero">
              <g transform="scale(5.12,5.12)">
                <path d="M26,2c-12.69141,0 -23,10.30859 -23,23c0,12.69141 10.30859,23 23,23c9.91797,0 15.97266,-4.5625 19.125,-10.21875c3.15234,-5.65625 3.55078,-12.30078 2.59375,-16.84375l-0.1875,-0.78125h-0.78125l-20.75,-0.03125h-1v10.40625h11.4375c-1.72656,4 -5.24219,6.75 -10.4375,6.75c-6.78906,0 -12.28125,-5.49219 -12.28125,-12.28125c0,-6.78906 5.49219,-12.28125 12.28125,-12.28125c3.05078,0 5.82031,1.12891 7.96875,2.96875l0.71875,0.59375l6.84375,-6.84375l0.71875,-0.75l-0.75,-0.6875c-4.08594,-3.72266 -9.53906,-6 -15.5,-6zM26,4c5.07422,0 9.65234,1.85547 13.28125,4.84375l-4.8125,4.8125c-2.37891,-1.77734 -5.26953,-2.9375 -8.46875,-2.9375c-7.87109,0 -14.28125,6.41016 -14.28125,14.28125c0,7.87109 6.41016,14.28125 14.28125,14.28125c6.55078,0 11.26172,-4.01562 12.9375,-9.46875l0.40625,-1.28125h-12.34375v-6.40625l18.84375,0.03125c0.66406,4.03516 0.22266,9.82813 -2.46875,14.65625c-2.85937,5.125 -8.05469,9.1875 -17.375,9.1875c-11.61328,0 -21,-9.39062 -21,-21c0,-11.60937 9.38672,-21 21,-21z"></path>
              </g>
            </g>
          </svg>
          <p className="text-sm font-medium text-stone-600 dark:text-stone-400">
            Login with Google
          </p>
        </>
      )}
    </button>

    <!-- GitHub Login Button -->
    <button
      disabled={loadingGitHub}
      onClick={() => {
        setLoadingGitHub(true);
        signIn("github");
      }}
      className={`${
        loadingGitHub
          ? "cursor-not-allowed bg-stone-50 dark:bg-stone-800"
          : "bg-white hover:bg-stone-50 active:bg-stone-100 dark:bg-black dark:hover:border-white dark:hover:bg-black"
      } group my-2 flex h-10 w-full items-center justify-center space-x-2 rounded-md border border-stone-200 transition-colors duration-75 focus:outline-none dark:border-stone-700`}
    >
      {loadingGitHub ? (
        <LoadingDots color="#A8A29E" />
      ) : (
        <>
          <svg
            className="h-4 w-4 text-black dark:text-white"
            aria-hidden="true"
            fill="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              clipRule="evenodd"
              d="M12 0C5.373 0 0 5.373 0 12c0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"
              fill="currentColor"
            />
          </svg>
          <p className="text-sm font-medium text-stone-600 dark:text-stone-400">
            Login with GitHub
          </p>
        </>
      )}
    </button>
  </>
);


```


Now you can login with google on production & or  github on local for testing purposes.

**Comment by brokoli777** [comment]
Was anyone able to get it working? I am able to go the google sign in screen but after clicking an account, the call back URL shows an error:  http://localhost:8888/login?callbackUrl=http%3A%2F%2Flocalhost%3A8888&error=OAuthCallback

**Comment by CrutchTheClutch** [comment]
May be a little convoluted but I was just trying to do something like this.  This is what I came up with as a workaround for local dev and it seems to work.  Basically, I just treated the root domain as a subdomain when developing locally.

I have some variables define that determine the domain I am targeting and will later use this in my middleware to filter where I want things to be routed.

```ts
export const ROOT_DOMAIN = `${ROOT}.com`;

export const ROOT_HOSTNAMES = new Set<string>([
  ROOT_DOMAIN,
  "root.localhost:3000",
]);

export const APP_DOMAIN =
  process.env.NEXT_PUBLIC_VERCEL_ENV === "production"
    ? `https://app.${ROOT_DOMAIN}`
    : "http://localhost:3000";

export const APP_HOSTNAMES = new Set<string>([
  `app.${ROOT_DOMAIN}`,
  "localhost:3000",
]);
```

The key here is making sure the root domain is treated as a subdomain `root.localhost:3000` and the subdomain we are targeting is treated as the root `localhost:3000`.

Next, my middleware function uses the previously defined variables to determine our routes.  I have the folders setup as the actual domain names for clarity here

```ts
export function middleware(req: NextRequest) {
  const { domain, path, key } = parse(req);

  // rewrite app to `/app.domain.com` folder
  if (APP_HOSTNAMES.has(domain)) {
    return NextResponse.rewrite(
      new URL(`/app.domain.com${path === "/" ? "" : path}`, req.url),
    );
  }

  // rewrite admin to `/admin.domain.com` folder
  if (ADMIN_HOSTNAMES.has(domain)) {
    return NextResponse.rewrite(
      new URL(`/admin.domain.com${path === "/" ? "" : path}`, req.url),
    );
  }

  // rewrite root to `/domain.com` folder
  if (ROOT_HOSTNAMES.has(domain)) {
    return NextResponse.rewrite(
      new URL(`/domain.com${path === "/" ? "" : path}`, req.url),
    );
  }

  // rewrite everything else to `/[domain]/[slug] dynamic route
  return NextResponse.rewrite(new URL(`/${domain}${path}`, req.url));
}
```

Lastly, we can now go target the standard `localhost:3000` and `http://localhost:3000/api/auth/callback/google` for our Google auth!

**Comment by prince-bansal** [comment]
> Hey @lexsemenenko! This is a known limitation with Google OAuth – just added a section in the guide on how to fix this: https://vercel.com/guides/nextjs-multi-tenant-application#4.-sign-in-with-google-limitations-in-localhost
> 
> ![CleanShot 2023-11-14 at 11 18 41](https://private-user-images.githubusercontent.com/28986134/282897934-6d144bd1-2216-4f10-a2d2-b3786d91faa5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMjM0ODAsIm5iZiI6MTcyMjMyMzE4MCwicGF0aCI6Ii8yODk4NjEzNC8yODI4OTc5MzQtNmQxNDRiZDEtMjIxNi00ZjEwLWEyZDItYjM3ODZkOTFmYWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA3MDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MzczYzEyODhhYjUxZGZkZjhkODFmNmFmNTI5YWMwMjJkOWJiNDgzYmFkZjkxOGZjZjllMjE2MWQxM2Y5OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tfWbXeJt3C1dlwHbst4oUkiYWZFBnecr9Jf9sJ6H_gE)

Will this work in the prod environment?
