### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by RightFootConsulting** [vercel/platforms#339]
I thought I would try out this template and ran the following command and got the following results which in my mind are a fail:

`steve@Trader MINGW64 ~/workspaces
$ npx create-next-app --example https://github.com/vercel/platforms shodan-palace
Creating a new Next.js app in C:\Users\steve\workspaces\shodan-palace.

Downloading files from repo https://github.com/vercel/platforms. This might take a moment.

Installing packages. This might take a couple of minutes.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: next@13.5.5-canary.0
npm ERR! node_modules/next
npm ERR!   next@"13.5.5-canary.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^12.2.5 || ^13" from next-auth@4.23.1
npm ERR! node_modules/next-auth
npm ERR!   next-auth@"4.23.1" from the root project
npm ERR!   peer next-auth@"^4" from @next-auth/prisma-adapter@1.0.7
npm ERR!   node_modules/@next-auth/prisma-adapter
npm ERR!     @next-auth/prisma-adapter@"^1.0.7" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\steve\AppData\Local\npm-cache\_logs\2023-10-25T14_01_26_571Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\steve\AppData\Local\npm-cache\_logs\2023-10-25T14_01_26_571Z-debug-0.log

Aborting installation.
  npm install has failed.

steve@Trader MINGW64 ~/workspaces
$ cat "C:\Users\steve\AppData\Local\npm-cache\_logs\2023-10-25T14_01_26_571Z-eresolve-report.txt"
'Log files:
C:\Users\steve\AppData\Local\npm-cache\_logs\2023-10-25T14_01_26_571Z-debug-0.log

# npm resolution error report

While resolving: undefined@undefined
Found: next@13.5.5-canary.0
node_modules/next
  next@"13.5.5-canary.0" from the root project

Could not resolve dependency:
peer next@"^12.2.5 || ^13" from next-auth@4.23.1
node_modules/next-auth
  next-auth@"4.23.1" from the root project
  peer next-auth@"^4" from @next-auth/prisma-adapter@1.0.7
  node_modules/@next-auth/prisma-adapter
    @next-auth/prisma-adapter@"^1.0.7" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

steve@Trader MINGW64 ~/workspaces
$ create-next-app --version
13.5.6`

**Comment by corytheinnocent** [comment]
Follow the guide. This is not the way.

**Comment by paulgould** [comment]
You can just ignore the error message and move onto the next step here: https://vercel.com/guides/nextjs-multi-tenant-application 

`npx create-next-app --example https://github.com/vercel/platforms platforms`

**Comment by steven-tey** [comment]
@RightFootConsulting as mentioned above, please follow the setup guide to ensure a successful set up of the Platforms Starter Kit: https://vercel.com/guides/nextjs-multi-tenant-application

Thank you!
