### ISSUE TITLE
Adding shadcn/ui breaks all the UI

### ISSUE THREAD

**Issue by FrancocDev** [vercel/platforms#344]
Hi, when I'm trying to install shadcn/ui, it brokes all the interface. 
I fix some of the errors due to the overwrite that makes on some files like utils, global.css and tailwind.config but still having some problems. Also, shadcn components apparently mess up with colors and that make that some components appear to be broken. 
Anyone has the same issue? 
Thanks in advance.

**Comment by leerob** [comment]
Hey, this is likely due to custom Tailwind configuration here. This library isn't currently set up to use Shadcn UI but maybe could in the future.

**Comment by itaykat** [comment]
@FrancocDev I had this issue while trying to use shadcn-ui in order to add a dark mode toggle on settings page, reach me out on telegram (itakat), lets join forces and maybe come with a dedicated PR

**Comment by FrancocDev** [comment]
Hi, I end up rebuilding all the dashboard with shadcn ui, something similar to the one that is on the demo of his site.
If you still want to connect for networking and discuss solutions/ideas, let me know and I will reach you :)
