### ISSUE TITLE
Fix environment variable name for GitHub

### ISSUE THREAD

**Issue by shoji-k** [vercel/platforms#35]
https://github.com/vercel/platforms/blob/beca9eb49b77742556d57098be6825867cb6a5d8/pages/api/auth/%5B...nextauth%5D.js#L9
https://github.com/vercel/platforms/blob/beca9eb49b77742556d57098be6825867cb6a5d8/pages/api/auth/%5B...nextauth%5D.js#L10

is not matched to

https://github.com/vercel/platforms/blob/beca9eb49b77742556d57098be6825867cb6a5d8/.env.example#L13
https://github.com/vercel/platforms/blob/beca9eb49b77742556d57098be6825867cb6a5d8/.env.example#L14

**Comment by steven-tey** [comment]
Whoops, good catch! Fixing now with #38

**Comment by steven-tey** [comment]
Fixed!
