### ISSUE TITLE
Upgrade next auth to v5

### ISSUE THREAD

**Issue by reymon359** [vercel/platforms#350]
Hey there 👋🏽  

I have just finished the tutorial from https://nextjs.org/learn and want to apply the best practices to a project that uses this template.

@steven-tey will this template be updated to use the newest next auth version like it has been done here https://github.com/vercel/next-learn/commit/abf301951d0499415408aec1594faa45f3e12026? 😄

**Comment by steven-tey** [comment]
No plans to do that currently, but we might revisit this in the future 🙏
