### ISSUE TITLE
Desperate need for help... The Middleware behaves unpredictabily and I can't get hostname

### ISSUE THREAD

**Issue by joaopedrosdmm** [vercel/platforms#370]
I'm tryng to use this repo to build a multitenant app, I have got everything working except the middleware. While using npm run dev it works fine, but while using vercel dev I don't seem to be able to get the request.nextUrl or host, hostname and so on...

I'm using Next 13.5.6 on page directory.

Code in the Middleware:

```
import { NextResponse } from 'next/server'
import { getHostnameDataOrDefault } from 'util/db'

export const config = {
  matcher: [ "/((?!api/|_next/|_static/|_vercel|[\\w-]+\\.\\w+).*)",],
}

export default async function middleware(req) {

  const url = req.nextUrl;

  // Get hostname of request (e.g. demo.vercel.pub, demo.localhost:3000)
  let hostname = req.headers
    .get("referer")
    .replace(".localhost:3000", `.${process.env.NEXT_PUBLIC_ROOT_DOMAIN}`)
    .replace("http:", "")
    .replaceAll("/", "")
  
  console.log(hostname)
  
  /*
  const { url, nextUrl } = req;
  const { host, hostname } = nextUrl;
  console.log({ url, host, hostname }); 
  */

  /*   
  const searchParams = req.nextUrl.searchParams.toString();
  // Get the pathname of the request (e.g. /, /about, /blog/first-post)
  const path = `${url.pathname}${
    searchParams.length > 0 ? `?${searchParams}` : ""
    }`; 
  */


  // Prevent security issues – users should not be able to canonically access
  // the pages/sites folder and its respective contents.
  if (url.pathname.startsWith(`/_sites`)) {
    console.log("here")
    url.pathname = `/404`
    
  } else {
    console.log('URL')
    // rewrite to the current subdomain under the pages/sites folder
    url.pathname = `/_sites/${hostname}${url.pathname}`
  }

  return NextResponse.rewrite(url)
}
```

**Comment by joaopedrosdmm** [comment]
I'm using the Vercel platform kit to build a multitenant app, I have got everything working except the middleware. While using npm run dev it works fine, but while using vercel dev I don't seem to be able to get the same request.

I'm using Next 13.5.6 on the page directory.

Code in the Middleware:

```
  const url = req.nextUrl;
  console.log(url)

  // Get hostname of request (e.g. demo.vercel.pub, demo.localhost:3000)
  let hostname = req.headers
    .get("host")
    .replace(".localhost:3000", `.${process.env.NEXT_PUBLIC_ROOT_DOMAIN}`);

  console.log(hostname)

  const searchParams = req.nextUrl.searchParams.toString();
  // Get the pathname of the request (e.g. /, /about, /blog/first-post)
  const path = `${url.pathname}${
    searchParams.length > 0 ? `?${searchParams}` : ""
  }`;
```

While using "npm run dev" on http://t222.localhost:3000/, a subdomain for testing I get the following for the url  and hostname: 

```
url {
  href: 'http://localhost:3000/?domain=t222.mydomain.com',
  origin: 'http://localhost:3000',
  ...
  host: 'localhost:3000',
  hostname: 'localhost',
  ...
  search: '?domain=t222.mydomain.com',
  searchParams: <ref *1> URLSearchParams {
  [Symbol(query)]: [ 'domain', 't222.mydomain.com' ],
  [Symbol(context)]: URL {
  [Symbol(context)]: URLContext {
  href: 'http://localhost:3000/?domain=t222.mydomain.com',
  ...
  },
  [Symbol(query)]: [Circular *1]
}

hostname t222.mydomain.com
```

For instance, while using "vercel dev" on the same subdomain, I get this for the URL and hostname:

```
url {
  href: 'http://localhost:3000/',
  origin: 'http://localhost:3000',
  ...
  host: 'localhost:3000',
  hostname: 'localhost',
  ...
  searchParams: <ref *1> URLSearchParams {
  [Symbol(query)]: [],
  [Symbol(context)]: URL {
  [Symbol(context)]: URLContext {
  href: 'http://localhost:3000/',
  ...
  },
  [Symbol(query)]: [Circular *1]
}

hostname [::1]:3000
```

 Why is this happening?

**Comment by janpawellek** [comment]
I have the same issue with `vercel dev`.

**Comment by vpaflah** [comment]
Did anyone of you added a wildcard entry in the project domain section(https://vercel.com/<team Name>/<Project Name>/settings/domains) in vercel?

Eg: *.demoapp.com

**Comment by joaopedrosdmm** [comment]
> Did anyone of you added a wildcard entry in the project domain section(https://vercel.com/teamName/projectName/settings/domains) in vercel?
> 
> Eg: *.demoapp.com

This is the way

**Comment by joaopedrosdmm** [comment]
> Did anyone of you added a wildcard entry in the project domain section(https://vercel.com/teamName/projectName/settings/domains) in vercel?
> 
> Eg: *.demoapp.com

This is the way.

You need to add a wild card.

**Comment by tutnyal** [comment]
@joaopedrosdmm @vpaflah

Does this work for a generated vercel demo site? something like https://platforms-tutnyals-tutnyals-projects.vercel.app/

and what would the wild card be? its not accepting *.platforms-tutnyal-tutnyals-projects.vercel.app/
![image](https://github.com/vercel/platforms/assets/16125367/c983e7e4-b4d9-43b8-8983-405b288f4bcf)

**Comment by tutnyal** [comment]
> @joaopedrosdmm @vpaflah
> 
> Does this work for a generated vercel demo site? something like https://platforms-tutnyals-tutnyals-projects.vercel.app/
> 
> and what would the wild card be? its not accepting *.platforms-tutnyal-tutnyals-projects.vercel.app/ ![image](https://private-user-images.githubusercontent.com/16125367/327939050-c983e7e4-b4d9-43b8-8983-405b288f4bcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MTYwODUsIm5iZiI6MTcxNDgxNTc4NSwicGF0aCI6Ii8xNjEyNTM2Ny8zMjc5MzkwNTAtYzk4M2U3ZTQtYjRkOS00M2I4LTg5ODMtNDA1YjI4OGY0YmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDA5NDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4OGQ2NGU5MmI5NTUwNzZjNGZhNjdkZjBhNDI3NjljNTQ5NGU3YjBlNmFjODRjYzc4MGVlZTdiOTE3NmExOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kLCN5JHPj1zqxXM8uD-alP1hXTq66kJ002e2TIJiqJ4)

I bought a $20 domain name and it helped. 

> I had the same error.
> 
> _The solution is to NOT skip the domain configuration on [this guide](https://vercel.com/guides/nextjs-multi-tenant-application#4.-configure-rewrites-for-multi-tenancy)_
> 
> **To explain further, I'll write the steps that solved for me:**
> 
> 1. Add your custom domain to your Vercel project domains settings:
> 
> * Add both your base domain (`yourdomain.com`) and also wildcard domain (`*.yourdomain.com`)
>   _As I have seen, .vercel.app domains don't work with wildcard, so you SHOULD  use a custom domain instead of .vercel.app_
> 
> 2. Add your domain to the `middleware.ts` file:
> 
> * Add `.yourdomain.com` [to this line](https://vercel.com/guides/nextjs-multi-tenant-application#4.-configure-rewrites-for-multi-tenancy) (replace `.vercel.pub` with your domain)
> * Add `yourdomain.com` [to this line](https://github.com/vercel/platforms/blob/main/middleware.ts#L51) (replace `platformize.vercel.app` with your domain)

This was very helpful. Thanks!

also, for those still facing the issue, do the above. Here is how I fixed mine.

My hostname or NEXT_PUBLIC_ROOT_DOMAIN is "ainime.me"

1. In vercel, don't forget to change the NEXT_PUBLIC_ROOT_DOMAIN under settings/environment variables.
![image](https://github.com/vercel/platforms/assets/16125367/37cf87d4-2330-4ec1-a649-0c80fed75ce4)

2. In your middleware.ts file, bc I added the wildcard domain(*.ainime.me" I made sure to add the "www" to my domain name. the "Get hostname of request" part of the code will change your host name to ".ainime.me" instead of "ainime.me" This will make the middleware think this is a page URL in your app/platform, but it doesn't exist so it returns a 404page not found. see what I did below.
` if (
    hostname === "www.ainime.me" || "ainime.me" ||
    hostname === process.env.NEXT_PUBLIC_ROOT_DOMAIN
  ) {
    return NextResponse.rewrite(
      new URL(`/home${path === "/" ? "" : path}`, req.url),
    );
  }`

3. now with this middleware.ts file change, in vercel under your project domain settings, make sure to forward the domain without the  "www." in front(ainime.me), to the one with it(www.ainime.me). See mine below
![image](https://github.com/vercel/platforms/assets/16125367/456f14d5-8da1-426f-894a-ef82b237283e)

I hope this helps, I spent 2 days on it.

**Comment by vpaflah** [comment]
> @joaopedrosdmm @vpaflah
> 
> Does this work for a generated vercel demo site? something like https://platforms-tutnyals-tutnyals-projects.vercel.app/

Yeah, you can add wildcard for this domain too.

> 
> and what would the wild card be? its not accepting *.platforms-tutnyal-tutnyals-projects.vercel.app/ 

You missed a .(dot) after * (asterisk), add `*.platforms-tutnyal-tutnyals-projects.vercel.app/` this and it will work as expected.
