### ISSUE TITLE
500 | Internal Server Error on blog posts

### ISSUE THREAD

**Issue by lwildermuth** [vercel/platforms#416]
Has anyone else experienced a 500 internal server error on blog posts after deployment?
Example URL: https://test-site.EXAMPLE.com/csrdcg308rwk7hmagrgdd2qt

**Comment by joshualinog** [comment]
@Sedong-Choi , i'm ignorant, but...

isn't this a bad thing? don't we want the pages to be rendered static for speed sake?

[https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config](url)
> 'force-dynamic': Force [dynamic rendering](https://nextjs.org/docs/app/building-your-application/rendering/server-components#dynamic-rendering), which will result in routes being rendered for each user at request time. This option is equivalent to getServerSideProps() in the pages directory.

**Comment by Sedong-Choi** [comment]
@joshualinog, I'm ignorant too. :)

I can find this. [Runtime differences](https://nextjs.org/docs/app/building-your-application/rendering/server-comComponents#runtime-differences)


<img width="657" alt="image" src="https://github.com/user-attachments/assets/e88b4b51-8c46-453a-8e7b-d402c8cdc4be">

I think when developing locally, the project uses the Node.js Runtime. However, Vercel production uses Edge Runtime.

So I think we should use `export const dynamic = 'force-dynamic';`.

**Comment by lwildermuth** [comment]
> I has 500 internal error '[app-static-to-dynamic-error](https://nextjs.org/docs/messages/app-static-to-dynamic-error)'
> 
> Plesae, Check vercel project's Log menu. If you see the text 'Static to Dynamic Error' text, add this code.
> 
> ```
> // app/[domain]/[slug]/page.tsx
> ...
> export const dynamic = 'force-dynamic';
> ...
> ```
> 
> Good Luck!

This worked for me! Thank you for your help @Sedong-Choi 

I'll close this issue
