### ISSUE TITLE
Following tutorials resulted in 404 not found error

### ISSUE THREAD

**Issue by harajune** [vercel/platforms#60]
Hi! I'm very excited about the multi-tenancy feature and tried the official tutorial below.
https://vercel.com/guides/nextjs-multi-tenant-application
However, after finishing the step5, the example site only shows 404 not found.

The example works well on local:3000. 
Could anyone help me to make the example work?

Also, I'm not familiar with Vercel. So, it is very appreciated to let me know the good way to debug this kind of problem.

The details are as below.
- deployed URL https://mkt-mng.tech/
- Source Code https://github.com/harajune/mt-test
  (I modified just .env)
- domain settings are as below:
![image](https://user-images.githubusercontent.com/56193/153703815-57723655-5f5d-4dee-a49e-3307139be86f.png)
- Environment Variables are as below
![image](https://user-images.githubusercontent.com/56193/153703845-e1889582-4262-4a45-89a2-815a17b479d9.png)

Thanks

**Comment by harajune** [comment]
I solved the problem by myself.
I had to replace the my domain with blank in hostname here.
https://github.com/vercel/platforms/blob/main/pages/_middleware.js#L17

**Comment by akashp1712** [comment]
Can you please explain the same with, vercel.app subdomains. The explanation on tutorial page is not easily understandable.
