### ISSUE TITLE
Add error toasts on login page

### ISSUE THREAD

**Issue by NuroDev** [vercel/platforms#7]
## What

A nice improvement to offer out of the box would be error prompts for the login page (User can see if it's an issue with something they did, or a server-side issue, etc). Seeing as `react-hot-toast` is already used in other places, we could use that combined with `next/router` to check for any error parameters returned by `next-auth`

**Comment by leerob** [comment]
Great feedback, thank you!

**Comment by ramprakashram** [comment]
Can I take up this issue ???

**Comment by leerob** [comment]
Yeah! That would be great. 

If there's an error logging in, catch that error and display it with `react-hot-toast` 👍

**Comment by ramprakashram** [comment]
Sure thanks @leerob

**Comment by ramprakashram** [comment]
Is there any markdown for setting the app to run locally ??

**Comment by NuroDev** [comment]
> Is there any markdown for setting the app to run locally ??

I highly recommend having a look through the [official guide](https://vercel.com/guides/nextjs-multi-tenant-application) @ramprakashram

**Comment by ramprakashram** [comment]
Thanks @NuroDev , I have now setup my local.

**Comment by steven-tey** [comment]
Thanks for taking the initiative @ramprakashram! Do let us know if you have any questions! :)

**Comment by amarpathak** [comment]
@leerob @steven-tey  I took this up as it was open for quite some time, please have a look at the PR, I am happy to make changes and push again if anything needs it. 

Thanks.

**Comment by amarpathak** [comment]
Done with #45 . We can close this.
