### ISSUE TITLE
Delete domain doesn't seem to work

### ISSUE THREAD

**Issue by Cosbgn** [vercel/platforms#70]
This Delete Domain API URL doesn't seem to work on my Vercel PRO team account.
[On line 7 if remove-domain.js](https://github.com/vercel/platforms/blob/bd5f5606267d59feaee45a781262f7b2165c3544/pages/api/remove-domain.js#L7)
```
DELETE    https://api.vercel.com/v8/projects/${process.env.VERCEL_PROJECT_ID}/domains/${domain}?teamId=${process.env.VERCEL_TEAM_ID}`
```

I found that instead the following one works:

```
DELETE    https://api.vercel.com/v6/domains/${domain}
```

It doesn't return any error, it simply doesn't delete the domain from my Vercel account

**Comment by steven-tey** [comment]
Great catch, thanks a lot @Cosbgn! Just fixed it with https://github.com/vercel/platforms/pull/105
