### ISSUE TITLE
error - TypeError: Expected "3000" to be a string

### ISSUE THREAD

**Issue by alimovz** [vercel/platforms#72]
Launching the app with `npm run dev`.
Accessing it via: `http://192.168.0.107:3000` from a different machine no the same subnet.
Get this in the logs on the server: 
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
(node:31041) ExperimentalWarning: The ESM module loader is experimental.
event - compiled client and server successfully in 314 ms (163 modules)
warn  - using beta Middleware (not covered by semver) - https://nextjs.org/docs/messages/beta-middleware
wait  - compiling /_middleware...
event - compiled client and server successfully in 136 
error - TypeError: Expected "3000" to be a string
```

And every time I refresh the page in the browser I get the `error - TypeError: Expected "3000" to be a string` error.

**Comment by thbwd** [comment]
Try accessing your site via `something.localhost:3000` instead. See https://github.com/vercel/platforms/blob/main/pages/_middleware.js#L19

**Comment by nicolasguasca1** [comment]
Having the same issue. It goes away with 

`    if (hostname === "localhost:3000") {
      url.pathname = `/`;
      return NextResponse.rewrite(url);
    }`

but when trying to access subdomains I set under pages, they are not found. It worked with next<12.1 :(

**Comment by jmotes** [comment]
@nicolasguasca1 have you upgraded to 12.1.1? If so, you'll need to adjust how you retrieve the host. 

`req.headers.get("host") ?? ""` should be replaced with `req.nextUrl.host`.

In my case, I'm grabbing the host and pathname at once now:

```
const { host, pathname } = req.nextUrl;
```

**Comment by nicolasguasca1** [comment]
Thanks for the reply @jmotes. I was trying to use `req.nextUrl.host` but when trying to access a different host (for example app.localhost:3000) it gets only the first order one (localhost:3000) so Im not being able to retrieving it well without the `req.headers.get("host")`. Do you know a work around?

**Comment by steven-tey** [comment]
Just updated `next` to `12.1.6` with https://github.com/vercel/platforms/pull/106 and everything seems to work fine.

@alimovz if you're accessing the app via `http://192.168.0.107:3000`, make sure that you replace all instances of `localhost:3000` with it in the [middleware file](https://github.com/vercel/platforms/blob/main/pages/_middleware.ts).

@nicolasguasca1 the correct syntax for getting hostname is [`req.header.get('host')`](https://github.com/vercel/platforms/blob/main/pages/_middleware.ts#L13), not `req.nextUrl.host`. With that, you'll be able to get the full URL (e.g.: `app.localhost:3000`)
