### ISSUE TITLE
Invalid domain setup instructions for subdomains

### ISSUE THREAD

**Issue by phbernard** [vercel/platforms#87]
When configuring a top level domain, eg. `example.com`, the setup instructions displayed by `DomainCard` are correct, showing the necessary records for both `example.com` (the A record) and `www.example.com` (the `www` CNAME record).

However, the instructions are wrong when using a subdomain, eg `sub.example.com`: 

![image](https://user-images.githubusercontent.com/423852/160371695-58cea6c5-462f-4ab1-bfa0-d124d5025c8f.png)

Here, the CNAME record is wrong: it should be `sub`, not `www`. And the A record is not applicable.

It seems to me that it should be:

![image](https://user-images.githubusercontent.com/423852/160372045-6276e900-f27f-4420-a5e8-ffc26d4389ab.png)

**Comment by steven-tey** [comment]
Great catch, thanks a lot @phbernard! Just fixed it with https://github.com/vercel/platforms/pull/108
