### ISSUE TITLE
Cannot read properties of undefined (reading 'customDomain')

### ISSUE THREAD

**Issue by qwanticode** [vercel/platforms#91]
Hey, 

When I try to add a custom domain I get this error either on app.vercel.pub or on an environment I recreated.

![image](https://user-images.githubusercontent.com/75182974/162484400-9df495c4-488f-4864-935b-8c83af7a8175.png)

**Comment by steven-tey** [comment]
Related to: https://github.com/vercel/platforms/issues/101

This should've been fixed with https://github.com/vercel/platforms/pull/105
