### ISSUE TITLE
Passing wrong argument on site>setting.tsx

### ISSUE THREAD

**Issue by Tze-Sien** [vercel/platforms#93]
In line 264 of setting.tsx it the code is passing in the **VALUE of the html input element** instead of EVENT
` await handleCustomDomain(e.currentTarget.customDomain.value);`

In line 154 of setting.tsx,  it is extracting the value again
`  async function handleCustomDomain(event: FormEvent<HTMLFormElement>) {
    const customDomain = event.currentTarget.customDomain.value;`

The solution:
I change line 264 to 
`await handleCustomDomain(e.currentTarget.customDomain.value);`

and I am able to add custom domain successfully

**Comment by qwanticode** [comment]
> The solution: I change line 264 to `await handleCustomDomain(e.currentTarget.customDomain.value);`

Hey, 

You pasted the same line as the original :) did you mean 'await handleCustomDomain(e);'

**Comment by Tze-Sien** [comment]
Yep absolutely! 

`await handleCustomDomain(e);`

**Comment by steven-tey** [comment]
@Tze-Sien @qwanticode apologies for the confusion, I made a mistake with the code before! This should be fixed with https://github.com/vercel/platforms/pull/105 :)
