### ISSUE TITLE
Wrong Mutate Key in Settings

### ISSUE THREAD

**Issue by msahajwani** [vercel/platforms#96]
Hello,

On this page:

https://github.com/vercel/platforms/tree/main/pages/app/site/[id]/settings.tsx

In function `saveSiteSettings()`, on line 99, You have this mutation:

`mutate(/api/get-site-settings?siteId=${siteId});`

Actually, there is no API with this URL with the name `get-site-settings`

The only API is `/api/site`

Can you please help with this or am I reading this incorrectly?

**Comment by steven-tey** [comment]
Great catch, thanks for the headsup @msahajwani! Just fixed it with https://github.com/vercel/platforms/pull/109
